# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.state_action_workflow_state import StateActionWorkflowState

class TestStateActionWorkflowState(unittest.TestCase):
    """StateActionWorkflowState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateActionWorkflowState:
        """Test StateActionWorkflowState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateActionWorkflowState`
        """
        model = StateActionWorkflowState()
        if include_optional:
            return StateActionWorkflowState(
                id = '',
                outputs = {
                    'key' : null
                    },
                populated = True,
                status = ''
            )
        else:
            return StateActionWorkflowState(
        )
        """

    def testStateActionWorkflowState(self):
        """Test StateActionWorkflowState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
