# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_create_app_branch_request import ServiceCreateAppBranchRequest

class TestServiceCreateAppBranchRequest(unittest.TestCase):
    """ServiceCreateAppBranchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceCreateAppBranchRequest:
        """Test ServiceCreateAppBranchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceCreateAppBranchRequest`
        """
        model = ServiceCreateAppBranchRequest()
        if include_optional:
            return ServiceCreateAppBranchRequest(
                connected_github_vcs_config_id = '',
                name = '0'
            )
        else:
            return ServiceCreateAppBranchRequest(
                connected_github_vcs_config_id = '',
                name = '0',
        )
        """

    def testServiceCreateAppBranchRequest(self):
        """Test ServiceCreateAppBranchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
