# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_update_runner_settings_request import ServiceUpdateRunnerSettingsRequest

class TestServiceUpdateRunnerSettingsRequest(unittest.TestCase):
    """ServiceUpdateRunnerSettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceUpdateRunnerSettingsRequest:
        """Test ServiceUpdateRunnerSettingsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceUpdateRunnerSettingsRequest`
        """
        model = ServiceUpdateRunnerSettingsRequest()
        if include_optional:
            return ServiceUpdateRunnerSettingsRequest(
                aws_max_instance_lifetime = 86400,
                container_image_tag = '',
                container_image_url = '',
                org_awsiam_role_arn = '',
                org_k8s_service_account_name = '',
                runner_api_url = ''
            )
        else:
            return ServiceUpdateRunnerSettingsRequest(
        )
        """

    def testServiceUpdateRunnerSettingsRequest(self):
        """Test ServiceUpdateRunnerSettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
