# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuon.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_action_workflow_config(self) -> None:
        """Test case for create_action_workflow_config

        create action workflow config
        """
        pass

    def test_create_app_action_workflow(self) -> None:
        """Test case for create_app_action_workflow

        create an app
        """
        pass

    def test_create_install_action_workflow_run(self) -> None:
        """Test case for create_install_action_workflow_run

        create an action workflow run for an install
        """
        pass

    def test_delete_action_workflow(self) -> None:
        """Test case for delete_action_workflow

        delete an app
        """
        pass

    def test_get_action_workflow(self) -> None:
        """Test case for get_action_workflow

        get an app action workflow
        """
        pass

    def test_get_action_workflow_config(self) -> None:
        """Test case for get_action_workflow_config

        get an app action workflow config
        """
        pass

    def test_get_action_workflow_configs(self) -> None:
        """Test case for get_action_workflow_configs

        get action workflow for an app
        """
        pass

    def test_get_action_workflow_latest_config(self) -> None:
        """Test case for get_action_workflow_latest_config

        get an app action workflow's latest config
        """
        pass

    def test_get_action_workflows(self) -> None:
        """Test case for get_action_workflows

        get action workflows for an app
        """
        pass

    def test_get_app_action_workflow(self) -> None:
        """Test case for get_app_action_workflow

        get an app action workflow
        """
        pass

    def test_get_install_action_workflow_recent_runs(self) -> None:
        """Test case for get_install_action_workflow_recent_runs

        get recent runs for an action workflow by install id
        """
        pass

    def test_get_install_action_workflow_run(self) -> None:
        """Test case for get_install_action_workflow_run

        get action workflow runs by install id and run id
        """
        pass

    def test_get_install_action_workflow_run_step(self) -> None:
        """Test case for get_install_action_workflow_run_step

        get action workflow run step by install id and step id
        """
        pass

    def test_get_install_action_workflow_runs(self) -> None:
        """Test case for get_install_action_workflow_runs

        get action workflow runs by install id
        """
        pass

    def test_get_install_action_workflows_latest_runs(self) -> None:
        """Test case for get_install_action_workflows_latest_runs

        get latest runs for all action workflows by install id
        """
        pass

    def test_update_app_action_workflow(self) -> None:
        """Test case for update_app_action_workflow

        patch an app
        """
        pass


if __name__ == '__main__':
    unittest.main()
