# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_workflow_step_approval_type import AppWorkflowStepApprovalType

class TestAppWorkflowStepApprovalType(unittest.TestCase):
    """AppWorkflowStepApprovalType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppWorkflowStepApprovalType(self):
        """Test AppWorkflowStepApprovalType"""
        # inst = AppWorkflowStepApprovalType()

if __name__ == '__main__':
    unittest.main()
