# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_azure_stack_outputs import AppAzureStackOutputs

class TestAppAzureStackOutputs(unittest.TestCase):
    """AppAzureStackOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAzureStackOutputs:
        """Test AppAzureStackOutputs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAzureStackOutputs`
        """
        model = AppAzureStackOutputs()
        if include_optional:
            return AppAzureStackOutputs(
                key_vault_id = '',
                key_vault_name = '',
                network_id = '',
                network_name = '',
                private_subnet_ids = [
                    ''
                    ],
                private_subnet_names = [
                    ''
                    ],
                public_subnet_ids = [
                    ''
                    ],
                public_subnet_names = [
                    ''
                    ],
                resource_group_id = '',
                resource_group_location = '',
                resource_group_name = '',
                subscription_id = '',
                subscription_tenant_id = ''
            )
        else:
            return AppAzureStackOutputs(
        )
        """

    def testAppAzureStackOutputs(self):
        """Test AppAzureStackOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
