# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_workflow_step_policy_validation import AppWorkflowStepPolicyValidation

class TestAppWorkflowStepPolicyValidation(unittest.TestCase):
    """AppWorkflowStepPolicyValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppWorkflowStepPolicyValidation:
        """Test AppWorkflowStepPolicyValidation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppWorkflowStepPolicyValidation`
        """
        model = AppWorkflowStepPolicyValidation()
        if include_optional:
            return AppWorkflowStepPolicyValidation(
                created_at = '',
                created_by_id = '',
                id = '',
                install_workflow_step_id = '',
                response = '',
                runner_job_id = '',
                status = nuon.models.app/composite_status.app.CompositeStatus(
                    created_at_ts = 56, 
                    created_by_id = '', 
                    history = [
                        nuon.models.app/composite_status.app.CompositeStatus(
                            created_at_ts = 56, 
                            created_by_id = '', 
                            metadata = {
                                'key' : null
                                }, 
                            status = 'error', 
                            status_human_description = '', )
                        ], 
                    metadata = {
                        'key' : null
                        }, 
                    status = 'error', 
                    status_human_description = '', ),
                updated_at = ''
            )
        else:
            return AppWorkflowStepPolicyValidation(
        )
        """

    def testAppWorkflowStepPolicyValidation(self):
        """Test AppWorkflowStepPolicyValidation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
