# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_teardown_install_components_request import ServiceTeardownInstallComponentsRequest

class TestServiceTeardownInstallComponentsRequest(unittest.TestCase):
    """ServiceTeardownInstallComponentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceTeardownInstallComponentsRequest:
        """Test ServiceTeardownInstallComponentsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceTeardownInstallComponentsRequest`
        """
        model = ServiceTeardownInstallComponentsRequest()
        if include_optional:
            return ServiceTeardownInstallComponentsRequest(
                error_behavior = '',
                plan_only = True
            )
        else:
            return ServiceTeardownInstallComponentsRequest(
        )
        """

    def testServiceTeardownInstallComponentsRequest(self):
        """Test ServiceTeardownInstallComponentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
