# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_aws_stack_outputs import AppAWSStackOutputs

class TestAppAWSStackOutputs(unittest.TestCase):
    """AppAWSStackOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAWSStackOutputs:
        """Test AppAWSStackOutputs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAWSStackOutputs`
        """
        model = AppAWSStackOutputs()
        if include_optional:
            return AppAWSStackOutputs(
                account_id = '',
                deprovision_iam_role_arn = '',
                maintenance_iam_role_arn = '',
                private_subnets = [
                    ''
                    ],
                provision_iam_role_arn = '',
                public_subnets = [
                    ''
                    ],
                region = '',
                runner_iam_role_arn = '',
                runner_subnet = '',
                vpc_id = ''
            )
        else:
            return AppAWSStackOutputs(
        )
        """

    def testAppAWSStackOutputs(self):
        """Test AppAWSStackOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
