# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_create_workflow_step_approval_response_request import ServiceCreateWorkflowStepApprovalResponseRequest

class TestServiceCreateWorkflowStepApprovalResponseRequest(unittest.TestCase):
    """ServiceCreateWorkflowStepApprovalResponseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceCreateWorkflowStepApprovalResponseRequest:
        """Test ServiceCreateWorkflowStepApprovalResponseRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceCreateWorkflowStepApprovalResponseRequest`
        """
        model = ServiceCreateWorkflowStepApprovalResponseRequest()
        if include_optional:
            return ServiceCreateWorkflowStepApprovalResponseRequest(
                note = '',
                response_type = 'deny'
            )
        else:
            return ServiceCreateWorkflowStepApprovalResponseRequest(
        )
        """

    def testServiceCreateWorkflowStepApprovalResponseRequest(self):
        """Test ServiceCreateWorkflowStepApprovalResponseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
