# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_runner_heart_beat import AppRunnerHeartBeat

class TestAppRunnerHeartBeat(unittest.TestCase):
    """AppRunnerHeartBeat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppRunnerHeartBeat:
        """Test AppRunnerHeartBeat
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppRunnerHeartBeat`
        """
        model = AppRunnerHeartBeat()
        if include_optional:
            return AppRunnerHeartBeat(
                alive_time = 56,
                created_at = '',
                created_by_id = '',
                id = '',
                runner_id = '',
                started_at = '',
                updated_at = '',
                version = ''
            )
        else:
            return AppRunnerHeartBeat(
        )
        """

    def testAppRunnerHeartBeat(self):
        """Test AppRunnerHeartBeat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
