# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_reprovision_install_sandbox_request import ServiceReprovisionInstallSandboxRequest

class TestServiceReprovisionInstallSandboxRequest(unittest.TestCase):
    """ServiceReprovisionInstallSandboxRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceReprovisionInstallSandboxRequest:
        """Test ServiceReprovisionInstallSandboxRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceReprovisionInstallSandboxRequest`
        """
        model = ServiceReprovisionInstallSandboxRequest()
        if include_optional:
            return ServiceReprovisionInstallSandboxRequest(
                plan_only = True
            )
        else:
            return ServiceReprovisionInstallSandboxRequest(
        )
        """

    def testServiceReprovisionInstallSandboxRequest(self):
        """Test ServiceReprovisionInstallSandboxRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
