# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_waitlist import AppWaitlist

class TestAppWaitlist(unittest.TestCase):
    """AppWaitlist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppWaitlist:
        """Test AppWaitlist
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppWaitlist`
        """
        model = AppWaitlist()
        if include_optional:
            return AppWaitlist(
                created_at = '',
                created_by_id = '',
                id = '',
                org_name = '',
                updated_at = ''
            )
        else:
            return AppWaitlist(
        )
        """

    def testAppWaitlist(self):
        """Test AppWaitlist"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
