# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_app_awsiam_policy_config import AppAppAWSIAMPolicyConfig

class TestAppAppAWSIAMPolicyConfig(unittest.TestCase):
    """AppAppAWSIAMPolicyConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAppAWSIAMPolicyConfig:
        """Test AppAppAWSIAMPolicyConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAppAWSIAMPolicyConfig`
        """
        model = AppAppAWSIAMPolicyConfig()
        if include_optional:
            return AppAppAWSIAMPolicyConfig(
                app_aws_iam_role_config_id = '',
                app_config_id = '',
                cloudformation_stack_name = '',
                contents = '',
                created_at = '',
                created_by_id = '',
                id = '',
                managed_policy_name = '',
                name = '',
                org_id = '',
                updated_at = ''
            )
        else:
            return AppAppAWSIAMPolicyConfig(
        )
        """

    def testAppAppAWSIAMPolicyConfig(self):
        """Test AppAppAWSIAMPolicyConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
