# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_terraform_workspace import AppTerraformWorkspace

class TestAppTerraformWorkspace(unittest.TestCase):
    """AppTerraformWorkspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppTerraformWorkspace:
        """Test AppTerraformWorkspace
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppTerraformWorkspace`
        """
        model = AppTerraformWorkspace()
        if include_optional:
            return AppTerraformWorkspace(
                created_at = '',
                created_by_id = '',
                id = '',
                org_id = '',
                owner_id = '',
                owner_type = '',
                updated_at = ''
            )
        else:
            return AppTerraformWorkspace(
        )
        """

    def testAppTerraformWorkspace(self):
        """Test AppTerraformWorkspace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
