# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_component_children import ServiceComponentChildren

class TestServiceComponentChildren(unittest.TestCase):
    """ServiceComponentChildren unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceComponentChildren:
        """Test ServiceComponentChildren
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceComponentChildren`
        """
        model = ServiceComponentChildren()
        if include_optional:
            return ServiceComponentChildren(
                children = [
                    nuon.models.app/component.app.Component(
                        app_id = '', 
                        config_versions = 56, 
                        created_at = '', 
                        created_by_id = '', 
                        dependencies = [
                            ''
                            ], 
                        id = '', 
                        links = {
                            'key' : null
                            }, 
                        name = '', 
                        resolved_var_name = '', 
                        status = '', 
                        status_description = '', 
                        type = 'terraform_module', 
                        updated_at = '', 
                        var_name = '', )
                    ]
            )
        else:
            return ServiceComponentChildren(
        )
        """

    def testServiceComponentChildren(self):
        """Test ServiceComponentChildren"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
