# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_app_stack_config import AppAppStackConfig

class TestAppAppStackConfig(unittest.TestCase):
    """AppAppStackConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAppStackConfig:
        """Test AppAppStackConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAppStackConfig`
        """
        model = AppAppStackConfig()
        if include_optional:
            return AppAppStackConfig(
                app_config_id = '',
                app_id = '',
                created_at = '',
                created_by_id = '',
                description = '',
                id = '',
                name = '',
                org_id = '',
                runner_nested_template_url = '',
                type = 'aws-cloudformation',
                updated_at = '',
                vpc_nested_template_url = ''
            )
        else:
            return AppAppStackConfig(
        )
        """

    def testAppAppStackConfig(self):
        """Test AppAppStackConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
