"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppRoleType(str, Enum):
    ORG_ADMIN = "org_admin"
    INSTALLER = "installer"
    RUNNER = "runner"
    HOSTED_INSTALLER = "hosted-installer"
