"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppAppPoliciesConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    org_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppAppPoliciesConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    org_id: Optional[str] = None

    updated_at: Optional[str] = None
