"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_appsecretconfig import AppAppSecretConfig, AppAppSecretConfigTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppAppSecretsConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    org_id: NotRequired[str]
    secrets: NotRequired[List[AppAppSecretConfigTypedDict]]
    updated_at: NotRequired[str]


class AppAppSecretsConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    org_id: Optional[str] = None

    secrets: Optional[List[AppAppSecretConfig]] = None

    updated_at: Optional[str] = None
