"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_stacktype import AppStackType
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppAppStackConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    description: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    org_id: NotRequired[str]
    runner_nested_template_url: NotRequired[str]
    type: NotRequired[AppStackType]
    updated_at: NotRequired[str]
    vpc_nested_template_url: NotRequired[str]


class AppAppStackConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    description: Optional[str] = None

    id: Optional[str] = None

    name: Optional[str] = None

    org_id: Optional[str] = None

    runner_nested_template_url: Optional[str] = None

    type: Optional[AppStackType] = None

    updated_at: Optional[str] = None

    vpc_nested_template_url: Optional[str] = None
