"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_apprunnertype import AppAppRunnerType
from .app_cloudplatform import AppCloudPlatform
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AppAppRunnerConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    app_runner_type: NotRequired[AppAppRunnerType]
    cloud_platform: NotRequired[AppCloudPlatform]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    env_vars: NotRequired[Dict[str, str]]
    helm_driver: NotRequired[str]
    id: NotRequired[str]
    init_script: NotRequired[str]
    r"""takes a URL to a bash script ⤵  which will be `curl | bash`-ed on the VM. usually via user-data or equivalent."""
    org_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppAppRunnerConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    app_runner_type: Optional[AppAppRunnerType] = None

    cloud_platform: Optional[AppCloudPlatform] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    env_vars: Optional[Dict[str, str]] = None

    helm_driver: Optional[str] = None

    id: Optional[str] = None

    init_script: Optional[str] = None
    r"""takes a URL to a bash script ⤵  which will be `curl | bash`-ed on the VM. usually via user-data or equivalent."""

    org_id: Optional[str] = None

    updated_at: Optional[str] = None
