"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppAWSIAMRoleType(str, Enum):
    RUNNER_PROVISION = "runner_provision"
    RUNNER_DEPROVISION = "runner_deprovision"
    RUNNER_MAINTENANCE = "runner_maintenance"
    BREAKGLASS = "breakglass"
    RUNNER_BREAKGLASS = "runner_breakglass"
