"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_connectedgithubvcsconfig import (
    AppConnectedGithubVCSConfig,
    AppConnectedGithubVCSConfigTypedDict,
)
from .app_publicgitvcsconfig import (
    AppPublicGitVCSConfig,
    AppPublicGitVCSConfigTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppActionWorkflowStepConfigTypedDict(TypedDict):
    action_workflow_config_id: NotRequired[str]
    app_config_id: NotRequired[str]
    r"""this belongs to an app config id"""
    app_id: NotRequired[str]
    command: NotRequired[str]
    connected_github_vcs_config: NotRequired[AppConnectedGithubVCSConfigTypedDict]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    env_vars: NotRequired[Dict[str, str]]
    id: NotRequired[str]
    idx: NotRequired[int]
    inline_contents: NotRequired[str]
    name: NotRequired[str]
    r"""metadata"""
    previous_step_id: NotRequired[str]
    public_git_vcs_config: NotRequired[AppPublicGitVCSConfigTypedDict]
    r"""all the details needed for a step"""
    references: NotRequired[List[str]]
    updated_at: NotRequired[str]


class AppActionWorkflowStepConfig(BaseModel):
    action_workflow_config_id: Optional[str] = None

    app_config_id: Optional[str] = None
    r"""this belongs to an app config id"""

    app_id: Optional[str] = None

    command: Optional[str] = None

    connected_github_vcs_config: Optional[AppConnectedGithubVCSConfig] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    env_vars: Optional[Dict[str, str]] = None

    id: Optional[str] = None

    idx: Optional[int] = None

    inline_contents: Optional[str] = None

    name: Optional[str] = None
    r"""metadata"""

    previous_step_id: Optional[str] = None

    public_git_vcs_config: Optional[AppPublicGitVCSConfig] = None
    r"""all the details needed for a step"""

    references: Optional[List[str]] = None

    updated_at: Optional[str] = None
