"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallerMetadataTypedDict(TypedDict):
    community_url: NotRequired[str]
    copyright_markdown: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    demo_url: NotRequired[str]
    description: NotRequired[str]
    documentation_url: NotRequired[str]
    favicon_url: NotRequired[str]
    footer_markdown: NotRequired[str]
    formatted_demo_url: NotRequired[str]
    github_url: NotRequired[str]
    homepage_url: NotRequired[str]
    id: NotRequired[str]
    installer_id: NotRequired[str]
    logo_url: NotRequired[str]
    name: NotRequired[str]
    og_image_url: NotRequired[str]
    post_install_markdown: NotRequired[str]
    updated_at: NotRequired[str]


class AppInstallerMetadata(BaseModel):
    community_url: Optional[str] = None

    copyright_markdown: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    demo_url: Optional[str] = None

    description: Optional[str] = None

    documentation_url: Optional[str] = None

    favicon_url: Optional[str] = None

    footer_markdown: Optional[str] = None

    formatted_demo_url: Optional[str] = None

    github_url: Optional[str] = None

    homepage_url: Optional[str] = None

    id: Optional[str] = None

    installer_id: Optional[str] = None

    logo_url: Optional[str] = None

    name: Optional[str] = None

    og_image_url: Optional[str] = None

    post_install_markdown: Optional[str] = None

    updated_at: Optional[str] = None
