"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_workflow import AppWorkflow, AppWorkflowTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppAppBranchTypedDict(TypedDict):
    app_id: NotRequired[str]
    connected_github_vcs_config_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    org_id: NotRequired[str]
    updated_at: NotRequired[str]
    workflows: NotRequired[List[AppWorkflowTypedDict]]


class AppAppBranch(BaseModel):
    app_id: Optional[str] = None

    connected_github_vcs_config_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    name: Optional[str] = None

    org_id: Optional[str] = None

    updated_at: Optional[str] = None

    workflows: Optional[List[AppWorkflow]] = None
