"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_runnerjob import AppRunnerJob, AppRunnerJobTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppTerraformWorkspaceStateJSONTypedDict(TypedDict):
    contents: NotRequired[List[int]]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    runner_job: NotRequired[AppRunnerJobTypedDict]
    runner_job_id: NotRequired[str]
    updated_at: NotRequired[str]
    workspace_id: NotRequired[str]
    r"""Foreign key to TerraformWorkspace with unique constraint to prevent conflicting states for a workspace"""


class AppTerraformWorkspaceStateJSON(BaseModel):
    contents: Optional[List[int]] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    runner_job: Optional[AppRunnerJob] = None

    runner_job_id: Optional[str] = None

    updated_at: Optional[str] = None

    workspace_id: Optional[str] = None
    r"""Foreign key to TerraformWorkspace with unique constraint to prevent conflicting states for a workspace"""
