"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppCloudPlatformRegionTypedDict(TypedDict):
    display_name: NotRequired[str]
    icon: NotRequired[str]
    name: NotRequired[str]
    value: NotRequired[str]


class AppCloudPlatformRegion(BaseModel):
    display_name: Optional[str] = None

    icon: Optional[str] = None

    name: Optional[str] = None

    value: Optional[str] = None
