"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_connectedgithubvcsconfig import (
    AppConnectedGithubVCSConfig,
    AppConnectedGithubVCSConfigTypedDict,
)
from .app_helmconfig import AppHelmConfig, AppHelmConfigTypedDict
from .app_publicgitvcsconfig import (
    AppPublicGitVCSConfig,
    AppPublicGitVCSConfigTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppHelmComponentConfigTypedDict(TypedDict):
    chart_name: NotRequired[str]
    r"""Helm specific configurations"""
    component_config_connection_id: NotRequired[str]
    r"""parent reference"""
    connected_github_vcs_config: NotRequired[AppConnectedGithubVCSConfigTypedDict]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    helm_config_json: NotRequired[AppHelmConfigTypedDict]
    id: NotRequired[str]
    namespace: NotRequired[str]
    public_git_vcs_config: NotRequired[AppPublicGitVCSConfigTypedDict]
    storage_driver: NotRequired[str]
    take_ownership: NotRequired[bool]
    r"""Newer config fields that we don't need a column for"""
    updated_at: NotRequired[str]
    values: NotRequired[Dict[str, str]]
    values_files: NotRequired[List[str]]


class AppHelmComponentConfig(BaseModel):
    chart_name: Optional[str] = None
    r"""Helm specific configurations"""

    component_config_connection_id: Optional[str] = None
    r"""parent reference"""

    connected_github_vcs_config: Optional[AppConnectedGithubVCSConfig] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    helm_config_json: Optional[AppHelmConfig] = None

    id: Optional[str] = None

    namespace: Optional[str] = None

    public_git_vcs_config: Optional[AppPublicGitVCSConfig] = None

    storage_driver: Optional[str] = None

    take_ownership: Optional[bool] = None
    r"""Newer config fields that we don't need a column for"""

    updated_at: Optional[str] = None

    values: Optional[Dict[str, str]] = None

    values_files: Optional[List[str]] = None
