"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_installstackoutputs import (
    AppInstallStackOutputs,
    AppInstallStackOutputsTypedDict,
)
from .app_installstackversion import (
    AppInstallStackVersion,
    AppInstallStackVersionTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallStackTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    install_stack_outputs: NotRequired[AppInstallStackOutputsTypedDict]
    org_id: NotRequired[str]
    updated_at: NotRequired[str]
    versions: NotRequired[List[AppInstallStackVersionTypedDict]]


class AppInstallStack(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    install_stack_outputs: Optional[AppInstallStackOutputs] = None

    org_id: Optional[str] = None

    updated_at: Optional[str] = None

    versions: Optional[List[AppInstallStackVersion]] = None
