"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppAppAWSIAMPolicyConfigTypedDict(TypedDict):
    app_aws_iam_role_config_id: NotRequired[str]
    app_config_id: NotRequired[str]
    cloudformation_stack_name: NotRequired[str]
    contents: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    managed_policy_name: NotRequired[str]
    name: NotRequired[str]
    org_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppAppAWSIAMPolicyConfig(BaseModel):
    app_aws_iam_role_config_id: Optional[str] = None

    app_config_id: Optional[str] = None

    cloudformation_stack_name: Optional[str] = None

    contents: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    managed_policy_name: Optional[str] = None

    name: Optional[str] = None

    org_id: Optional[str] = None

    updated_at: Optional[str] = None
