"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppAWSStackOutputsTypedDict(TypedDict):
    account_id: NotRequired[str]
    deprovision_iam_role_arn: NotRequired[str]
    maintenance_iam_role_arn: NotRequired[str]
    private_subnets: NotRequired[List[str]]
    provision_iam_role_arn: NotRequired[str]
    public_subnets: NotRequired[List[str]]
    region: NotRequired[str]
    runner_iam_role_arn: NotRequired[str]
    runner_subnet: NotRequired[str]
    vpc_id: NotRequired[str]


class AppAWSStackOutputs(BaseModel):
    account_id: Optional[str] = None

    deprovision_iam_role_arn: Optional[str] = None

    maintenance_iam_role_arn: Optional[str] = None

    private_subnets: Optional[List[str]] = None

    provision_iam_role_arn: Optional[str] = None

    public_subnets: Optional[List[str]] = None

    region: Optional[str] = None

    runner_iam_role_arn: Optional[str] = None

    runner_subnet: Optional[str] = None

    vpc_id: Optional[str] = None
