"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_actionworkflowstepconfig import (
    AppActionWorkflowStepConfig,
    AppActionWorkflowStepConfigTypedDict,
)
from .app_actionworkflowtriggerconfig import (
    AppActionWorkflowTriggerConfig,
    AppActionWorkflowTriggerConfigTypedDict,
)
from .refs_ref import RefsRef, RefsRefTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppActionWorkflowConfigTypedDict(TypedDict):
    action_workflow_id: NotRequired[str]
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    component_dependency_ids: NotRequired[List[str]]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    references: NotRequired[List[str]]
    refs: NotRequired[List[RefsRefTypedDict]]
    steps: NotRequired[List[AppActionWorkflowStepConfigTypedDict]]
    timeout: NotRequired[int]
    triggers: NotRequired[List[AppActionWorkflowTriggerConfigTypedDict]]
    r"""INFO: if adding new associations here, ensure they are added to the batch delete activity"""
    updated_at: NotRequired[str]


class AppActionWorkflowConfig(BaseModel):
    action_workflow_id: Optional[str] = None

    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    component_dependency_ids: Optional[List[str]] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    references: Optional[List[str]] = None

    refs: Optional[List[RefsRef]] = None

    steps: Optional[List[AppActionWorkflowStepConfig]] = None

    timeout: Optional[int] = None

    triggers: Optional[List[AppActionWorkflowTriggerConfig]] = None
    r"""INFO: if adding new associations here, ensure they are added to the batch delete activity"""

    updated_at: Optional[str] = None
