"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_account import AppAccount, AppAccountTypedDict
from .app_appsandboxconfig import AppAppSandboxConfig, AppAppSandboxConfigTypedDict
from .app_compositestatus import AppCompositeStatus, AppCompositeStatusTypedDict
from .app_logstream import AppLogStream, AppLogStreamTypedDict
from .app_runnerjob import AppRunnerJob, AppRunnerJobTypedDict
from .app_sandboxruntype import AppSandboxRunType
from nuon.types import BaseModel
from typing import Any, Dict, List, Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .app_installactionworkflowrun import (
        AppInstallActionWorkflowRun,
        AppInstallActionWorkflowRunTypedDict,
    )
    from .app_workflow import AppWorkflow, AppWorkflowTypedDict


class AppInstallSandboxRunTypedDict(TypedDict):
    action_workflow_runs: NotRequired[List["AppInstallActionWorkflowRunTypedDict"]]
    app_sandbox_config: NotRequired[AppAppSandboxConfigTypedDict]
    created_at: NotRequired[str]
    created_by: NotRequired[AppAccountTypedDict]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    install_sandbox_id: NotRequired[str]
    r"""TODO: once we run a backfill we can make this non pointer"""
    install_workflow_id: NotRequired[str]
    log_stream: NotRequired[AppLogStreamTypedDict]
    outputs: NotRequired[Dict[str, Any]]
    run_type: NotRequired[AppSandboxRunType]
    runner_jobs: NotRequired[List[AppRunnerJobTypedDict]]
    r"""runner details"""
    status: NotRequired[str]
    status_description: NotRequired[str]
    status_v2: NotRequired[AppCompositeStatusTypedDict]
    updated_at: NotRequired[str]
    workflow: NotRequired["AppWorkflowTypedDict"]
    workflow_id: NotRequired[str]
    r"""Fields that are de-nested at read time using AfterQuery"""


class AppInstallSandboxRun(BaseModel):
    action_workflow_runs: Optional[List["AppInstallActionWorkflowRun"]] = None

    app_sandbox_config: Optional[AppAppSandboxConfig] = None

    created_at: Optional[str] = None

    created_by: Optional[AppAccount] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    install_sandbox_id: Optional[str] = None
    r"""TODO: once we run a backfill we can make this non pointer"""

    install_workflow_id: Optional[str] = None

    log_stream: Optional[AppLogStream] = None

    outputs: Optional[Dict[str, Any]] = None

    run_type: Optional[AppSandboxRunType] = None

    runner_jobs: Optional[List[AppRunnerJob]] = None
    r"""runner details"""

    status: Optional[str] = None

    status_description: Optional[str] = None

    status_v2: Optional[AppCompositeStatus] = None

    updated_at: Optional[str] = None

    workflow: Optional["AppWorkflow"] = None

    workflow_id: Optional[str] = None
    r"""Fields that are de-nested at read time using AfterQuery"""
