"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_installapprovaloption import AppInstallApprovalOption
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallConfigTypedDict(TypedDict):
    approval_option: NotRequired[AppInstallApprovalOption]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    org_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppInstallConfig(BaseModel):
    approval_option: Optional[AppInstallApprovalOption] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    org_id: Optional[str] = None

    updated_at: Optional[str] = None
