"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_appawsiamroleconfig import (
    AppAppAWSIAMRoleConfig,
    AppAppAWSIAMRoleConfigTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppAppPermissionsConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    aws_iam_roles: NotRequired[List[AppAppAWSIAMRoleConfigTypedDict]]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    deprovision_aws_iam_role: NotRequired[AppAppAWSIAMRoleConfigTypedDict]
    id: NotRequired[str]
    maintenance_aws_iam_role: NotRequired[AppAppAWSIAMRoleConfigTypedDict]
    org_id: NotRequired[str]
    provision_aws_iam_role: NotRequired[AppAppAWSIAMRoleConfigTypedDict]
    r"""loaded via an after query"""
    updated_at: NotRequired[str]


class AppAppPermissionsConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    aws_iam_roles: Optional[List[AppAppAWSIAMRoleConfig]] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    deprovision_aws_iam_role: Optional[AppAppAWSIAMRoleConfig] = None

    id: Optional[str] = None

    maintenance_aws_iam_role: Optional[AppAppAWSIAMRoleConfig] = None

    org_id: Optional[str] = None

    provision_aws_iam_role: Optional[AppAppAWSIAMRoleConfig] = None
    r"""loaded via an after query"""

    updated_at: Optional[str] = None
