"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppAppRunnerType(str, Enum):
    UNKNOWN = "unknown"
    AWS_ECS = "aws-ecs"
    AWS_EKS = "aws-eks"
    AZURE_AKS = "azure-aks"
    AZURE_ACS = "azure-acs"
    LOCAL = "local"
    AWS = "aws"
    AZURE = "azure"
