"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_installactionworkflowrunstepstatus import (
    AppInstallActionWorkflowRunStepStatus,
)
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallActionWorkflowRunStepTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    execution_duration: NotRequired[int]
    id: NotRequired[str]
    install_action_workflow_run_id: NotRequired[str]
    status: NotRequired[AppInstallActionWorkflowRunStepStatus]
    step_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppInstallActionWorkflowRunStep(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    execution_duration: Optional[int] = None

    id: Optional[str] = None

    install_action_workflow_run_id: Optional[str] = None

    status: Optional[AppInstallActionWorkflowRunStepStatus] = None

    step_id: Optional[str] = None

    updated_at: Optional[str] = None
