"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppCloudPlatform(str, Enum):
    AWS = "aws"
    AZURE = "azure"
    UNKNOWN = "unknown"
