"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_terraformstateinstance import (
    AppTerraformStateInstance,
    AppTerraformStateInstanceTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppTerraformStateResourceTypedDict(TypedDict):
    instances: NotRequired[List[AppTerraformStateInstanceTypedDict]]
    mode: NotRequired[str]
    name: NotRequired[str]
    provider: NotRequired[str]
    type: NotRequired[str]


class AppTerraformStateResource(BaseModel):
    instances: Optional[List[AppTerraformStateInstance]] = None

    mode: Optional[str] = None

    name: Optional[str] = None

    provider: Optional[str] = None

    type: Optional[str] = None
