"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_connectedgithubvcsconfig import (
    AppConnectedGithubVCSConfig,
    AppConnectedGithubVCSConfigTypedDict,
)
from .app_publicgitvcsconfig import (
    AppPublicGitVCSConfig,
    AppPublicGitVCSConfigTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppAppSandboxConfigTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    aws_region_type: NotRequired[str]
    r"""cloud specific fields"""
    cloud_platform: NotRequired[str]
    r"""fields set via after query"""
    connected_github_vcs_config: NotRequired[AppConnectedGithubVCSConfigTypedDict]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    env_vars: NotRequired[Dict[str, str]]
    id: NotRequired[str]
    org_id: NotRequired[str]
    public_git_vcs_config: NotRequired[AppPublicGitVCSConfigTypedDict]
    terraform_version: NotRequired[str]
    updated_at: NotRequired[str]
    variables: NotRequired[Dict[str, str]]
    variables_files: NotRequired[List[str]]


class AppAppSandboxConfig(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    aws_region_type: Optional[str] = None
    r"""cloud specific fields"""

    cloud_platform: Optional[str] = None
    r"""fields set via after query"""

    connected_github_vcs_config: Optional[AppConnectedGithubVCSConfig] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    env_vars: Optional[Dict[str, str]] = None

    id: Optional[str] = None

    org_id: Optional[str] = None

    public_git_vcs_config: Optional[AppPublicGitVCSConfig] = None

    terraform_version: Optional[str] = None

    updated_at: Optional[str] = None

    variables: Optional[Dict[str, str]] = None

    variables_files: Optional[List[str]] = None
