"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_policyname import AppPolicyName
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AppPolicyTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[AppPolicyName]
    permissions: NotRequired[Dict[str, str]]
    r"""Permissions are used to track granular permissions for each domain"""
    role_id: NotRequired[str]
    updated_at: NotRequired[str]


class AppPolicy(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    name: Optional[AppPolicyName] = None

    permissions: Optional[Dict[str, str]] = None
    r"""Permissions are used to track granular permissions for each domain"""

    role_id: Optional[str] = None

    updated_at: Optional[str] = None
