"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_operationstatus import AppOperationStatus
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallEventTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    operation: NotRequired[str]
    operation_name: NotRequired[str]
    operation_status: NotRequired[AppOperationStatus]
    org_id: NotRequired[str]
    payload: NotRequired[Dict[str, str]]
    updated_at: NotRequired[str]


class AppInstallEvent(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    operation: Optional[str] = None

    operation_name: Optional[str] = None

    operation_status: Optional[AppOperationStatus] = None

    org_id: Optional[str] = None

    payload: Optional[Dict[str, str]] = None

    updated_at: Optional[str] = None
