"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppRunnerOperationType(str, Enum):
    PROVISION = "provision"
    PROVISION_SERVICE_ACCOUNT = "provision_service_account"
    REPROVISION = "reprovision"
    DEPROVISION = "deprovision"
