"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_component import AppComponent, AppComponentTypedDict
from .app_componentbuildstatus import AppComponentBuildStatus
from .app_componentconfigconnection import (
    AppComponentConfigConnection,
    AppComponentConfigConnectionTypedDict,
)
from .app_installdeploystatus import AppInstallDeployStatus
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallComponentSummaryTypedDict(TypedDict):
    build_status: NotRequired[AppComponentBuildStatus]
    build_status_description: NotRequired[str]
    component_config: NotRequired[AppComponentConfigConnectionTypedDict]
    component_id: NotRequired[str]
    component_name: NotRequired[str]
    dependencies: NotRequired[List[AppComponentTypedDict]]
    deploy_status: NotRequired[AppInstallDeployStatus]
    deploy_status_description: NotRequired[str]
    id: NotRequired[str]


class AppInstallComponentSummary(BaseModel):
    build_status: Optional[AppComponentBuildStatus] = None

    build_status_description: Optional[str] = None

    component_config: Optional[AppComponentConfigConnection] = None

    component_id: Optional[str] = None

    component_name: Optional[str] = None

    dependencies: Optional[List[AppComponent]] = None

    deploy_status: Optional[AppInstallDeployStatus] = None

    deploy_status_description: Optional[str] = None

    id: Optional[str] = None
