"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_runnerjobexecutionoutputs import (
    AppRunnerJobExecutionOutputs,
    AppRunnerJobExecutionOutputsTypedDict,
)
from .app_runnerjobexecutionresult import (
    AppRunnerJobExecutionResult,
    AppRunnerJobExecutionResultTypedDict,
)
from .app_runnerjobexecutionstatus import AppRunnerJobExecutionStatus
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppRunnerJobExecutionTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    org_id: NotRequired[str]
    outputs: NotRequired[AppRunnerJobExecutionOutputsTypedDict]
    result: NotRequired[AppRunnerJobExecutionResultTypedDict]
    runner_job_id: NotRequired[str]
    status: NotRequired[AppRunnerJobExecutionStatus]
    updated_at: NotRequired[str]


class AppRunnerJobExecution(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    org_id: Optional[str] = None

    outputs: Optional[AppRunnerJobExecutionOutputs] = None

    result: Optional[AppRunnerJobExecutionResult] = None

    runner_job_id: Optional[str] = None

    status: Optional[AppRunnerJobExecutionStatus] = None

    updated_at: Optional[str] = None
