"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallStateTypedDict(TypedDict):
    archived: NotRequired[bool]
    contents: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    triggered_by_id: NotRequired[str]
    triggered_by_type: NotRequired[str]
    updated_at: NotRequired[str]
    version: NotRequired[int]


class AppInstallState(BaseModel):
    archived: Optional[bool] = None

    contents: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    triggered_by_id: Optional[str] = None

    triggered_by_type: Optional[str] = None

    updated_at: Optional[str] = None

    version: Optional[int] = None
