"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_componenttype import AppComponentType
from .app_dockerbuildcomponentconfig import (
    AppDockerBuildComponentConfig,
    AppDockerBuildComponentConfigTypedDict,
)
from .app_externalimagecomponentconfig import (
    AppExternalImageComponentConfig,
    AppExternalImageComponentConfigTypedDict,
)
from .app_helmcomponentconfig import (
    AppHelmComponentConfig,
    AppHelmComponentConfigTypedDict,
)
from .app_jobcomponentconfig import (
    AppJobComponentConfig,
    AppJobComponentConfigTypedDict,
)
from .app_kubernetesmanifestcomponentconfig import (
    AppKubernetesManifestComponentConfig,
    AppKubernetesManifestComponentConfigTypedDict,
)
from .app_terraformmodulecomponentconfig import (
    AppTerraformModuleComponentConfig,
    AppTerraformModuleComponentConfigTypedDict,
)
from .refs_ref import RefsRef, RefsRefTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppComponentConfigConnectionTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_config_version: NotRequired[int]
    checksum: NotRequired[str]
    component_dependency_ids: NotRequired[List[str]]
    component_id: NotRequired[str]
    component_name: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    docker_build: NotRequired[AppDockerBuildComponentConfigTypedDict]
    external_image: NotRequired[AppExternalImageComponentConfigTypedDict]
    helm: NotRequired[AppHelmComponentConfigTypedDict]
    id: NotRequired[str]
    job: NotRequired[AppJobComponentConfigTypedDict]
    kubernetes_manifest: NotRequired[AppKubernetesManifestComponentConfigTypedDict]
    references: NotRequired[List[str]]
    refs: NotRequired[List[RefsRefTypedDict]]
    terraform_module: NotRequired[AppTerraformModuleComponentConfigTypedDict]
    type: NotRequired[AppComponentType]
    updated_at: NotRequired[str]
    version: NotRequired[int]


class AppComponentConfigConnection(BaseModel):
    app_config_id: Optional[str] = None

    app_config_version: Optional[int] = None

    checksum: Optional[str] = None

    component_dependency_ids: Optional[List[str]] = None

    component_id: Optional[str] = None

    component_name: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    docker_build: Optional[AppDockerBuildComponentConfig] = None

    external_image: Optional[AppExternalImageComponentConfig] = None

    helm: Optional[AppHelmComponentConfig] = None

    id: Optional[str] = None

    job: Optional[AppJobComponentConfig] = None

    kubernetes_manifest: Optional[AppKubernetesManifestComponentConfig] = None

    references: Optional[List[str]] = None

    refs: Optional[List[RefsRef]] = None

    terraform_module: Optional[AppTerraformModuleComponentConfig] = None

    type: Optional[AppComponentType] = None

    updated_at: Optional[str] = None

    version: Optional[int] = None
