"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_apprunnerconfig import AppAppRunnerConfig, AppAppRunnerConfigTypedDict
from .app_appsandboxconfig import AppAppSandboxConfig, AppAppSandboxConfigTypedDict
from .app_awsaccount import AppAWSAccount, AppAWSAccountTypedDict
from .app_azureaccount import AppAzureAccount, AppAzureAccountTypedDict
from .app_installactionworkflow import (
    AppInstallActionWorkflow,
    AppInstallActionWorkflowTypedDict,
)
from .app_installcomponent import AppInstallComponent, AppInstallComponentTypedDict
from .app_installconfig import AppInstallConfig, AppInstallConfigTypedDict
from .app_installevent import AppInstallEvent, AppInstallEventTypedDict
from .app_installinputs import AppInstallInputs, AppInstallInputsTypedDict
from .app_installsandbox import AppInstallSandbox, AppInstallSandboxTypedDict
from .app_installsandboxrun import AppInstallSandboxRun, AppInstallSandboxRunTypedDict
from .app_installstack import AppInstallStack, AppInstallStackTypedDict
from .app_installstate import AppInstallState, AppInstallStateTypedDict
from .app_workflow import AppWorkflow, AppWorkflowTypedDict
from nuon.types import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    app_id: NotRequired[str]
    app_runner_config: NotRequired[AppAppRunnerConfigTypedDict]
    app_sandbox_config: NotRequired[AppAppSandboxConfigTypedDict]
    aws_account: NotRequired[AppAWSAccountTypedDict]
    azure_account: NotRequired[AppAzureAccountTypedDict]
    cloud_platform: NotRequired[str]
    component_statuses: NotRequired[Dict[str, str]]
    composite_component_status: NotRequired[str]
    composite_component_status_description: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_action_workflows: NotRequired[List[AppInstallActionWorkflowTypedDict]]
    install_components: NotRequired[List[AppInstallComponentTypedDict]]
    install_config: NotRequired[AppInstallConfigTypedDict]
    install_events: NotRequired[List[AppInstallEventTypedDict]]
    install_inputs: NotRequired[List[AppInstallInputsTypedDict]]
    install_number: NotRequired[int]
    install_sandbox_runs: NotRequired[List[AppInstallSandboxRunTypedDict]]
    install_stack: NotRequired[AppInstallStackTypedDict]
    install_states: NotRequired[List[AppInstallStateTypedDict]]
    links: NotRequired[Dict[str, Any]]
    name: NotRequired[str]
    runner_id: NotRequired[str]
    runner_status: NotRequired[str]
    runner_status_description: NotRequired[str]
    runner_type: NotRequired[str]
    sandbox: NotRequired[AppInstallSandboxTypedDict]
    sandbox_status: NotRequired[str]
    sandbox_status_description: NotRequired[str]
    status: NotRequired[str]
    r"""TODO(jm): deprecate these fields once the terraform provider has been updated"""
    status_description: NotRequired[str]
    updated_at: NotRequired[str]
    workflows: NotRequired[List[AppWorkflowTypedDict]]


class AppInstall(BaseModel):
    app_config_id: Optional[str] = None

    app_id: Optional[str] = None

    app_runner_config: Optional[AppAppRunnerConfig] = None

    app_sandbox_config: Optional[AppAppSandboxConfig] = None

    aws_account: Optional[AppAWSAccount] = None

    azure_account: Optional[AppAzureAccount] = None

    cloud_platform: Optional[str] = None

    component_statuses: Optional[Dict[str, str]] = None

    composite_component_status: Optional[str] = None

    composite_component_status_description: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_action_workflows: Optional[List[AppInstallActionWorkflow]] = None

    install_components: Optional[List[AppInstallComponent]] = None

    install_config: Optional[AppInstallConfig] = None

    install_events: Optional[List[AppInstallEvent]] = None

    install_inputs: Optional[List[AppInstallInputs]] = None

    install_number: Optional[int] = None

    install_sandbox_runs: Optional[List[AppInstallSandboxRun]] = None

    install_stack: Optional[AppInstallStack] = None

    install_states: Optional[List[AppInstallState]] = None

    links: Optional[Dict[str, Any]] = None

    name: Optional[str] = None

    runner_id: Optional[str] = None

    runner_status: Optional[str] = None

    runner_status_description: Optional[str] = None

    runner_type: Optional[str] = None

    sandbox: Optional[AppInstallSandbox] = None

    sandbox_status: Optional[str] = None

    sandbox_status_description: Optional[str] = None

    status: Optional[str] = None
    r"""TODO(jm): deprecate these fields once the terraform provider has been updated"""

    status_description: Optional[str] = None

    updated_at: Optional[str] = None

    workflows: Optional[List[AppWorkflow]] = None
