"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppVCSConnectionCommitTypedDict(TypedDict):
    author_email: NotRequired[str]
    author_name: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    message: NotRequired[str]
    sha: NotRequired[str]
    updated_at: NotRequired[str]
    vcs_connection_id: NotRequired[str]


class AppVCSConnectionCommit(BaseModel):
    author_email: Optional[str] = None

    author_name: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    message: Optional[str] = None

    sha: Optional[str] = None

    updated_at: Optional[str] = None

    vcs_connection_id: Optional[str] = None
