"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_account import AppAccount, AppAccountTypedDict
from .app_componentconfigconnection import (
    AppComponentConfigConnection,
    AppComponentConfigConnectionTypedDict,
)
from .app_compositestatus import AppCompositeStatus, AppCompositeStatusTypedDict
from .app_logstream import AppLogStream, AppLogStreamTypedDict
from .app_runnerjob import AppRunnerJob, AppRunnerJobTypedDict
from .app_vcsconnectioncommit import (
    AppVCSConnectionCommit,
    AppVCSConnectionCommitTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .app_componentrelease import AppComponentRelease, AppComponentReleaseTypedDict
    from .app_installdeploy import AppInstallDeploy, AppInstallDeployTypedDict


class AppComponentBuildTypedDict(TypedDict):
    checksum: NotRequired[str]
    r"""checksum of our intermediate component config"""
    component_config_connection: NotRequired[AppComponentConfigConnectionTypedDict]
    component_config_connection_id: NotRequired[str]
    r"""DEPRECATED: will retain the field to connect against the last component config connection that set this build"""
    component_config_version: NotRequired[int]
    component_id: NotRequired[str]
    r"""Read-only fields set on the object to de-nest data"""
    component_name: NotRequired[str]
    created_at: NotRequired[str]
    created_by: NotRequired[AppAccountTypedDict]
    created_by_id: NotRequired[str]
    git_ref: NotRequired[str]
    id: NotRequired[str]
    install_deploys: NotRequired[List["AppInstallDeployTypedDict"]]
    log_stream: NotRequired[AppLogStreamTypedDict]
    releases: NotRequired[List["AppComponentReleaseTypedDict"]]
    runner_job: NotRequired[AppRunnerJobTypedDict]
    r"""runner details"""
    status: NotRequired[str]
    status_description: NotRequired[str]
    status_v2: NotRequired[AppCompositeStatusTypedDict]
    updated_at: NotRequired[str]
    vcs_connection_commit: NotRequired[AppVCSConnectionCommitTypedDict]


class AppComponentBuild(BaseModel):
    checksum: Optional[str] = None
    r"""checksum of our intermediate component config"""

    component_config_connection: Optional[AppComponentConfigConnection] = None

    component_config_connection_id: Optional[str] = None
    r"""DEPRECATED: will retain the field to connect against the last component config connection that set this build"""

    component_config_version: Optional[int] = None

    component_id: Optional[str] = None
    r"""Read-only fields set on the object to de-nest data"""

    component_name: Optional[str] = None

    created_at: Optional[str] = None

    created_by: Optional[AppAccount] = None

    created_by_id: Optional[str] = None

    git_ref: Optional[str] = None

    id: Optional[str] = None

    install_deploys: Optional[List["AppInstallDeploy"]] = None

    log_stream: Optional[AppLogStream] = None

    releases: Optional[List["AppComponentRelease"]] = None

    runner_job: Optional[AppRunnerJob] = None
    r"""runner details"""

    status: Optional[str] = None

    status_description: Optional[str] = None

    status_v2: Optional[AppCompositeStatus] = None

    updated_at: Optional[str] = None

    vcs_connection_commit: Optional[AppVCSConnectionCommit] = None
