"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppKubernetesManifestComponentConfigTypedDict(TypedDict):
    component_config_connection_id: NotRequired[str]
    r"""value"""
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    manifest: NotRequired[str]
    namespace: NotRequired[str]
    updated_at: NotRequired[str]


class AppKubernetesManifestComponentConfig(BaseModel):
    component_config_connection_id: Optional[str] = None
    r"""value"""

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    manifest: Optional[str] = None

    namespace: Optional[str] = None

    updated_at: Optional[str] = None
