"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AppInstallActionWorkflowRunStepStatus(str, Enum):
    FINISHED = "finished"
    PENDING = "pending"
    IN_PROGRESS = "in-progress"
    TIMED_OUT = "timed-out"
    ERROR = "error"
