"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_actionworkflow import AppActionWorkflow, AppActionWorkflowTypedDict
from nuon.types import BaseModel
from typing import List, Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .app_installactionworkflowrun import (
        AppInstallActionWorkflowRun,
        AppInstallActionWorkflowRunTypedDict,
    )


class AppInstallActionWorkflowTypedDict(TypedDict):
    action_workflow: NotRequired[AppActionWorkflowTypedDict]
    action_workflow_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    runs: NotRequired[List["AppInstallActionWorkflowRunTypedDict"]]
    status: NotRequired[str]
    r"""after query fields filled in after querying"""
    updated_at: NotRequired[str]


class AppInstallActionWorkflow(BaseModel):
    action_workflow: Optional[AppActionWorkflow] = None

    action_workflow_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    runs: Optional[List["AppInstallActionWorkflowRun"]] = None

    status: Optional[str] = None
    r"""after query fields filled in after querying"""

    updated_at: Optional[str] = None
