"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppJobComponentConfigTypedDict(TypedDict):
    args: NotRequired[List[str]]
    cmd: NotRequired[List[str]]
    component_config_connection_id: NotRequired[str]
    r"""value"""
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    env_vars: NotRequired[Dict[str, str]]
    id: NotRequired[str]
    image_url: NotRequired[str]
    r"""Image attributes, copied from a docker_buid or external_image component."""
    tag: NotRequired[str]
    updated_at: NotRequired[str]


class AppJobComponentConfig(BaseModel):
    args: Optional[List[str]] = None

    cmd: Optional[List[str]] = None

    component_config_connection_id: Optional[str] = None
    r"""value"""

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    env_vars: Optional[Dict[str, str]] = None

    id: Optional[str] = None

    image_url: Optional[str] = None
    r"""Image attributes, copied from a docker_buid or external_image component."""

    tag: Optional[str] = None

    updated_at: Optional[str] = None
