"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .app_appinputgroup import AppAppInputGroup, AppAppInputGroupTypedDict


class AppAppInputTypedDict(TypedDict):
    app_input_id: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    default: NotRequired[str]
    description: NotRequired[str]
    display_name: NotRequired[str]
    group: NotRequired["AppAppInputGroupTypedDict"]
    group_id: NotRequired[str]
    id: NotRequired[str]
    index: NotRequired[int]
    internal: NotRequired[bool]
    name: NotRequired[str]
    org_id: NotRequired[str]
    required: NotRequired[bool]
    sensitive: NotRequired[bool]
    type: NotRequired[str]
    updated_at: NotRequired[str]


class AppAppInput(BaseModel):
    app_input_id: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    default: Optional[str] = None

    description: Optional[str] = None

    display_name: Optional[str] = None

    group: Optional["AppAppInputGroup"] = None

    group_id: Optional[str] = None

    id: Optional[str] = None

    index: Optional[int] = None

    internal: Optional[bool] = None

    name: Optional[str] = None

    org_id: Optional[str] = None

    required: Optional[bool] = None

    sensitive: Optional[bool] = None

    type: Optional[str] = None

    updated_at: Optional[str] = None
