"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AppLogStreamTypedDict(TypedDict):
    attrs: NotRequired[Dict[str, str]]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    open: NotRequired[bool]
    org_id: NotRequired[str]
    owner_id: NotRequired[str]
    owner_type: NotRequired[str]
    runner_api_url: NotRequired[str]
    updated_at: NotRequired[str]
    write_token: NotRequired[str]


class AppLogStream(BaseModel):
    attrs: Optional[Dict[str, str]] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    open: Optional[bool] = None

    org_id: Optional[str] = None

    owner_id: Optional[str] = None

    owner_type: Optional[str] = None

    runner_api_url: Optional[str] = None

    updated_at: Optional[str] = None

    write_token: Optional[str] = None
