"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_compositestatus import AppCompositeStatus, AppCompositeStatusTypedDict
from .app_installsandboxrun import AppInstallSandboxRun, AppInstallSandboxRunTypedDict
from .app_terraformworkspace import (
    AppTerraformWorkspace,
    AppTerraformWorkspaceTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AppInstallSandboxTypedDict(TypedDict):
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    id: NotRequired[str]
    install_id: NotRequired[str]
    install_sandbox_runs: NotRequired[List[AppInstallSandboxRunTypedDict]]
    status: NotRequired[str]
    status_description: NotRequired[str]
    status_v2: NotRequired[AppCompositeStatusTypedDict]
    terraform_workspace: NotRequired[AppTerraformWorkspaceTypedDict]
    updated_at: NotRequired[str]


class AppInstallSandbox(BaseModel):
    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    id: Optional[str] = None

    install_id: Optional[str] = None

    install_sandbox_runs: Optional[List[AppInstallSandboxRun]] = None

    status: Optional[str] = None

    status_description: Optional[str] = None

    status_v2: Optional[AppCompositeStatus] = None

    terraform_workspace: Optional[AppTerraformWorkspace] = None

    updated_at: Optional[str] = None
