"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppRunnerGroupSettingsTypedDict(TypedDict):
    aws_cloudformation_stack_type: NotRequired[str]
    aws_instance_type: NotRequired[str]
    r"""aws runner specifics runner-v2"""
    aws_max_instance_lifetime: NotRequired[int]
    r"""Default: 7 days"""
    aws_tags: NotRequired[Dict[str, str]]
    container_image_tag: NotRequired[str]
    container_image_url: NotRequired[str]
    r"""configuration for deploying the runner"""
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    enable_logging: NotRequired[bool]
    enable_metrics: NotRequired[bool]
    enable_sentry: NotRequired[bool]
    groups: NotRequired[List[str]]
    r"""the job loop groups the runner should poll for"""
    heart_beat_timeout: NotRequired[int]
    r"""Various settings for the runner to handle internally"""
    id: NotRequired[str]
    local_aws_iam_role_arn: NotRequired[str]
    logging_level: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    r"""Metadata is used as both log and metric tags/attributes in the runner when emitting data"""
    org_aws_iam_role_arn: NotRequired[str]
    r"""org runner specifics"""
    org_id: NotRequired[str]
    org_k8s_service_account_name: NotRequired[str]
    otel_collector_config: NotRequired[str]
    platform: NotRequired[str]
    r"""platform variable for use in the runner"""
    runner_api_url: NotRequired[str]
    runner_group_id: NotRequired[str]
    sandbox_mode: NotRequired[bool]
    r"""configuration for managing the runner server side"""
    updated_at: NotRequired[str]


class AppRunnerGroupSettings(BaseModel):
    aws_cloudformation_stack_type: Optional[str] = None

    aws_instance_type: Optional[str] = None
    r"""aws runner specifics runner-v2"""

    aws_max_instance_lifetime: Optional[int] = None
    r"""Default: 7 days"""

    aws_tags: Optional[Dict[str, str]] = None

    container_image_tag: Optional[str] = None

    container_image_url: Optional[str] = None
    r"""configuration for deploying the runner"""

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    enable_logging: Optional[bool] = None

    enable_metrics: Optional[bool] = None

    enable_sentry: Optional[bool] = None

    groups: Optional[List[str]] = None
    r"""the job loop groups the runner should poll for"""

    heart_beat_timeout: Optional[int] = None
    r"""Various settings for the runner to handle internally"""

    id: Optional[str] = None

    local_aws_iam_role_arn: Optional[str] = None

    logging_level: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None
    r"""Metadata is used as both log and metric tags/attributes in the runner when emitting data"""

    org_aws_iam_role_arn: Optional[str] = None
    r"""org runner specifics"""

    org_id: Optional[str] = None

    org_k8s_service_account_name: Optional[str] = None

    otel_collector_config: Optional[str] = None

    platform: Optional[str] = None
    r"""platform variable for use in the runner"""

    runner_api_url: Optional[str] = None

    runner_group_id: Optional[str] = None

    sandbox_mode: Optional[bool] = None
    r"""configuration for managing the runner server side"""

    updated_at: Optional[str] = None
