"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppPublicGitVCSConfigTypedDict(TypedDict):
    branch: NotRequired[str]
    component_config_id: NotRequired[str]
    component_config_type: NotRequired[str]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    directory: NotRequired[str]
    id: NotRequired[str]
    repo: NotRequired[str]
    r"""actual configuration"""
    updated_at: NotRequired[str]


class AppPublicGitVCSConfig(BaseModel):
    branch: Optional[str] = None

    component_config_id: Optional[str] = None

    component_config_type: Optional[str] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    directory: Optional[str] = None

    id: Optional[str] = None

    repo: Optional[str] = None
    r"""actual configuration"""

    updated_at: Optional[str] = None
