"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_connectedgithubvcsconfig import (
    AppConnectedGithubVCSConfig,
    AppConnectedGithubVCSConfigTypedDict,
)
from .app_publicgitvcsconfig import (
    AppPublicGitVCSConfig,
    AppPublicGitVCSConfigTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AppDockerBuildComponentConfigTypedDict(TypedDict):
    build_args: NotRequired[List[str]]
    component_config_connection_id: NotRequired[str]
    r"""value"""
    connected_github_vcs_config: NotRequired[AppConnectedGithubVCSConfigTypedDict]
    created_at: NotRequired[str]
    created_by_id: NotRequired[str]
    dockerfile: NotRequired[str]
    env_vars: NotRequired[Dict[str, str]]
    id: NotRequired[str]
    public_git_vcs_config: NotRequired[AppPublicGitVCSConfigTypedDict]
    target: NotRequired[str]
    updated_at: NotRequired[str]


class AppDockerBuildComponentConfig(BaseModel):
    build_args: Optional[List[str]] = None

    component_config_connection_id: Optional[str] = None
    r"""value"""

    connected_github_vcs_config: Optional[AppConnectedGithubVCSConfig] = None

    created_at: Optional[str] = None

    created_by_id: Optional[str] = None

    dockerfile: Optional[str] = None

    env_vars: Optional[Dict[str, str]] = None

    id: Optional[str] = None

    public_git_vcs_config: Optional[AppPublicGitVCSConfig] = None

    target: Optional[str] = None

    updated_at: Optional[str] = None
