"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createapprunnerconfigrequest import (
    ServiceCreateAppRunnerConfigRequest,
    ServiceCreateAppRunnerConfigRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAppRunnerConfigSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class CreateAppRunnerConfigSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class CreateAppRunnerConfigRequestTypedDict(TypedDict):
    app_id: str
    r"""app ID"""
    service_create_app_runner_config_request: (
        ServiceCreateAppRunnerConfigRequestTypedDict
    )
    r"""Input"""


class CreateAppRunnerConfigRequest(BaseModel):
    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""app ID"""

    service_create_app_runner_config_request: Annotated[
        ServiceCreateAppRunnerConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
