"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createhelmcomponentconfigrequest import (
    ServiceCreateHelmComponentConfigRequest,
    ServiceCreateHelmComponentConfigRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateHelmComponentConfigSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class CreateHelmComponentConfigSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class CreateHelmComponentConfigRequestTypedDict(TypedDict):
    component_id: str
    r"""component ID"""
    service_create_helm_component_config_request: (
        ServiceCreateHelmComponentConfigRequestTypedDict
    )
    r"""Input"""


class CreateHelmComponentConfigRequest(BaseModel):
    component_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""component ID"""

    service_create_helm_component_config_request: Annotated[
        ServiceCreateHelmComponentConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
