"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createkubernetesmanifestcomponentconfigrequest import (
    ServiceCreateKubernetesManifestComponentConfigRequest,
    ServiceCreateKubernetesManifestComponentConfigRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateKubernetesManifestComponentConfigSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class CreateKubernetesManifestComponentConfigSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class CreateKubernetesManifestComponentConfigRequestTypedDict(TypedDict):
    component_id: str
    r"""component ID"""
    service_create_kubernetes_manifest_component_config_request: (
        ServiceCreateKubernetesManifestComponentConfigRequestTypedDict
    )
    r"""Input"""


class CreateKubernetesManifestComponentConfigRequest(BaseModel):
    component_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""component ID"""

    service_create_kubernetes_manifest_component_config_request: Annotated[
        ServiceCreateKubernetesManifestComponentConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
