"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createinstallactionworkflowrunrequest import (
    ServiceCreateInstallActionWorkflowRunRequest,
    ServiceCreateInstallActionWorkflowRunRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateInstallActionWorkflowRunSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class CreateInstallActionWorkflowRunSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class CreateInstallActionWorkflowRunRequestTypedDict(TypedDict):
    install_id: str
    r"""install ID"""
    service_create_install_action_workflow_run_request: (
        ServiceCreateInstallActionWorkflowRunRequestTypedDict
    )
    r"""Input"""


class CreateInstallActionWorkflowRunRequest(BaseModel):
    install_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""install ID"""

    service_create_install_action_workflow_run_request: Annotated[
        ServiceCreateInstallActionWorkflowRunRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
