"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createactionworkflowconfigrequest import (
    ServiceCreateActionWorkflowConfigRequest,
    ServiceCreateActionWorkflowConfigRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateActionWorkflowConfigSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class CreateActionWorkflowConfigSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class CreateActionWorkflowConfigRequestTypedDict(TypedDict):
    action_workflow_id: str
    r"""action workflow ID"""
    service_create_action_workflow_config_request: (
        ServiceCreateActionWorkflowConfigRequestTypedDict
    )
    r"""Input"""


class CreateActionWorkflowConfigRequest(BaseModel):
    action_workflow_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""action workflow ID"""

    service_create_action_workflow_config_request: Annotated[
        ServiceCreateActionWorkflowConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
