"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_deprovisioninstallsandboxrequest import (
    ServiceDeprovisionInstallSandboxRequest,
    ServiceDeprovisionInstallSandboxRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeprovisionInstallSandboxSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class DeprovisionInstallSandboxSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class DeprovisionInstallSandboxRequestTypedDict(TypedDict):
    install_id: str
    r"""install ID"""
    service_deprovision_install_sandbox_request: (
        ServiceDeprovisionInstallSandboxRequestTypedDict
    )
    r"""Input"""


class DeprovisionInstallSandboxRequest(BaseModel):
    install_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""install ID"""

    service_deprovision_install_sandbox_request: Annotated[
        ServiceDeprovisionInstallSandboxRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
