"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    SecurityMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRunnerJobsSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class GetRunnerJobsSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class GetRunnerJobsRequestTypedDict(TypedDict):
    runner_id: str
    r"""runner ID"""
    group: NotRequired[str]
    r"""job group"""
    groups: NotRequired[str]
    r"""job groups"""
    status: NotRequired[str]
    r"""job status"""
    statuses: NotRequired[str]
    r"""job statuses"""
    offset: NotRequired[int]
    r"""offset of jobs to return"""
    limit: NotRequired[int]
    r"""limit of jobs to return"""
    page: NotRequired[int]
    r"""page number of results to return"""
    x_nuon_pagination_enabled: NotRequired[bool]
    r"""Enable pagination"""


class GetRunnerJobsRequest(BaseModel):
    runner_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""runner ID"""

    group: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""job group"""

    groups: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""job groups"""

    status: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""job status"""

    statuses: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""job statuses"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""offset of jobs to return"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""limit of jobs to return"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""page number of results to return"""

    x_nuon_pagination_enabled: Annotated[
        Optional[bool],
        pydantic.Field(alias="x-nuon-pagination-enabled"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Enable pagination"""
