"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .refs_reftype import RefsRefType
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RefsRefTypedDict(TypedDict):
    input: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[RefsRefType]
    value: NotRequired[str]


class RefsRef(BaseModel):
    input: Optional[str] = None

    name: Optional[str] = None

    type: Optional[RefsRefType] = None

    value: Optional[str] = None
