"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_retryworkflowbyidrequest import (
    ServiceRetryWorkflowByIDRequest,
    ServiceRetryWorkflowByIDRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RetryOwnerWorkflowByIDSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class RetryOwnerWorkflowByIDSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class RetryOwnerWorkflowByIDRequestTypedDict(TypedDict):
    workflow_id: str
    r"""workflow ID"""
    service_retry_workflow_by_id_request: ServiceRetryWorkflowByIDRequestTypedDict
    r"""Input"""


class RetryOwnerWorkflowByIDRequest(BaseModel):
    workflow_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""workflow ID"""

    service_retry_workflow_by_id_request: Annotated[
        ServiceRetryWorkflowByIDRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
