"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceReprovisionInstallSandboxRequestTypedDict(TypedDict):
    plan_only: NotRequired[bool]


class ServiceReprovisionInstallSandboxRequest(BaseModel):
    plan_only: Optional[bool] = None
