"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateInstallerRequestMetadataTypedDict(TypedDict):
    community_url: str
    description: str
    documentation_url: str
    favicon_url: str
    github_url: str
    homepage_url: str
    logo_url: str
    copyright_markdown: NotRequired[str]
    demo_url: NotRequired[str]
    footer_markdown: NotRequired[str]
    og_image_url: NotRequired[str]
    post_install_markdown: NotRequired[str]


class ServiceCreateInstallerRequestMetadata(BaseModel):
    community_url: str

    description: str

    documentation_url: str

    favicon_url: str

    github_url: str

    homepage_url: str

    logo_url: str

    copyright_markdown: Optional[str] = None

    demo_url: Optional[str] = None

    footer_markdown: Optional[str] = None

    og_image_url: Optional[str] = None

    post_install_markdown: Optional[str] = None


class ServiceCreateInstallerRequestTypedDict(TypedDict):
    app_ids: List[str]
    name: str
    metadata: NotRequired[ServiceCreateInstallerRequestMetadataTypedDict]


class ServiceCreateInstallerRequest(BaseModel):
    app_ids: List[str]

    name: str

    metadata: Optional[ServiceCreateInstallerRequestMetadata] = None
