"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class StrategyTypedDict(TypedDict):
    delay: NotRequired[str]
    installs_per_step: NotRequired[int]


class Strategy(BaseModel):
    delay: Optional[str] = None

    installs_per_step: Optional[int] = None


class ServiceCreateComponentReleaseRequestTypedDict(TypedDict):
    auto_build: NotRequired[bool]
    build_id: NotRequired[str]
    install_ids: NotRequired[List[str]]
    strategy: NotRequired[StrategyTypedDict]


class ServiceCreateComponentReleaseRequest(BaseModel):
    auto_build: Optional[bool] = None

    build_id: Optional[str] = None

    install_ids: Optional[List[str]] = None

    strategy: Optional[Strategy] = None
