"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateOrgRequestTypedDict(TypedDict):
    name: str
    use_sandbox_mode: NotRequired[bool]
    r"""These fields are used to control the behaviour of the org."""


class ServiceCreateOrgRequest(BaseModel):
    name: str

    use_sandbox_mode: Optional[bool] = None
    r"""These fields are used to control the behaviour of the org."""
