"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_createactionworkflowconfigsteprequest import (
    ServiceCreateActionWorkflowConfigStepRequest,
    ServiceCreateActionWorkflowConfigStepRequestTypedDict,
)
from .service_createactionworkflowconfigtriggerrequest import (
    ServiceCreateActionWorkflowConfigTriggerRequest,
    ServiceCreateActionWorkflowConfigTriggerRequestTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateActionWorkflowConfigRequestTypedDict(TypedDict):
    app_config_id: str
    steps: List[ServiceCreateActionWorkflowConfigStepRequestTypedDict]
    triggers: List[ServiceCreateActionWorkflowConfigTriggerRequestTypedDict]
    dependencies: NotRequired[List[str]]
    references: NotRequired[List[str]]
    timeout: NotRequired[int]


class ServiceCreateActionWorkflowConfigRequest(BaseModel):
    app_config_id: str

    steps: List[ServiceCreateActionWorkflowConfigStepRequest]

    triggers: List[ServiceCreateActionWorkflowConfigTriggerRequest]

    dependencies: Optional[List[str]] = None

    references: Optional[List[str]] = None

    timeout: Optional[int] = None
