"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_app import AppApp, AppAppTypedDict
from .app_installermetadata import AppInstallerMetadata, AppInstallerMetadataTypedDict
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceRenderedInstallerTypedDict(TypedDict):
    apps: NotRequired[List[AppAppTypedDict]]
    metadata: NotRequired[AppInstallerMetadataTypedDict]
    sandbox_mode: NotRequired[bool]


class ServiceRenderedInstaller(BaseModel):
    apps: Optional[List[AppApp]] = None

    metadata: Optional[AppInstallerMetadata] = None

    sandbox_mode: Optional[bool] = None
