"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class ServiceUpdateInstallInputsRequestTypedDict(TypedDict):
    inputs: Dict[str, str]


class ServiceUpdateInstallInputsRequest(BaseModel):
    inputs: Dict[str, str]
