"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_connectedgithubvcssandboxconfigrequest import (
    ServiceConnectedGithubVCSSandboxConfigRequest,
    ServiceConnectedGithubVCSSandboxConfigRequestTypedDict,
)
from .service_publicgitvcssandboxconfigrequest import (
    ServicePublicGitVCSSandboxConfigRequest,
    ServicePublicGitVCSSandboxConfigRequestTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateAppSandboxConfigRequestTypedDict(TypedDict):
    env_vars: Dict[str, str]
    terraform_version: str
    variables: Dict[str, str]
    app_config_id: NotRequired[str]
    connected_github_vcs_config: NotRequired[
        ServiceConnectedGithubVCSSandboxConfigRequestTypedDict
    ]
    public_git_vcs_config: NotRequired[ServicePublicGitVCSSandboxConfigRequestTypedDict]
    variables_files: NotRequired[List[str]]


class ServiceCreateAppSandboxConfigRequest(BaseModel):
    env_vars: Dict[str, str]

    terraform_version: str

    variables: Dict[str, str]

    app_config_id: Optional[str] = None

    connected_github_vcs_config: Optional[
        ServiceConnectedGithubVCSSandboxConfigRequest
    ] = None

    public_git_vcs_config: Optional[ServicePublicGitVCSSandboxConfigRequest] = None

    variables_files: Optional[List[str]] = None
