"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_appawsiampolicyconfig import (
    ServiceAppAWSIAMPolicyConfig,
    ServiceAppAWSIAMPolicyConfigTypedDict,
)
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceAppAWSIAMRoleConfigTypedDict(TypedDict):
    description: str
    display_name: str
    name: str
    permissions_boundary: NotRequired[str]
    policies: NotRequired[List[ServiceAppAWSIAMPolicyConfigTypedDict]]


class ServiceAppAWSIAMRoleConfig(BaseModel):
    description: str

    display_name: str

    name: str

    permissions_boundary: Optional[str] = None

    policies: Optional[List[ServiceAppAWSIAMPolicyConfig]] = None
