"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_connectedgithubvcsconfigrequest import (
    ServiceConnectedGithubVCSConfigRequest,
    ServiceConnectedGithubVCSConfigRequestTypedDict,
)
from .service_publicgitvcsconfigrequest import (
    ServicePublicGitVCSConfigRequest,
    ServicePublicGitVCSConfigRequestTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateHelmComponentConfigRequestTypedDict(TypedDict):
    chart_name: str
    values: Dict[str, str]
    app_config_id: NotRequired[str]
    checksum: NotRequired[str]
    connected_github_vcs_config: NotRequired[
        ServiceConnectedGithubVCSConfigRequestTypedDict
    ]
    dependencies: NotRequired[List[str]]
    namespace: NotRequired[str]
    public_git_vcs_config: NotRequired[ServicePublicGitVCSConfigRequestTypedDict]
    references: NotRequired[List[str]]
    storage_driver: NotRequired[str]
    take_ownership: NotRequired[bool]
    values_files: NotRequired[List[str]]


class ServiceCreateHelmComponentConfigRequest(BaseModel):
    chart_name: str

    values: Dict[str, str]

    app_config_id: Optional[str] = None

    checksum: Optional[str] = None

    connected_github_vcs_config: Optional[ServiceConnectedGithubVCSConfigRequest] = None

    dependencies: Optional[List[str]] = None

    namespace: Optional[str] = None

    public_git_vcs_config: Optional[ServicePublicGitVCSConfigRequest] = None

    references: Optional[List[str]] = None

    storage_driver: Optional[str] = None

    take_ownership: Optional[bool] = None

    values_files: Optional[List[str]] = None
