"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateKubernetesManifestComponentConfigRequestTypedDict(TypedDict):
    app_config_id: NotRequired[str]
    checksum: NotRequired[str]
    dependencies: NotRequired[List[str]]
    manifest: NotRequired[str]
    namespace: NotRequired[str]
    references: NotRequired[List[str]]


class ServiceCreateKubernetesManifestComponentConfigRequest(BaseModel):
    app_config_id: Optional[str] = None

    checksum: Optional[str] = None

    dependencies: Optional[List[str]] = None

    manifest: Optional[str] = None

    namespace: Optional[str] = None

    references: Optional[List[str]] = None
