"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceRunnerConnectionStatusTypedDict(TypedDict):
    connected: NotRequired[bool]
    latest_heartbeat_timestamp: NotRequired[int]


class ServiceRunnerConnectionStatus(BaseModel):
    connected: Optional[bool] = None

    latest_heartbeat_timestamp: Optional[int] = None
