"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_appconfigversion import AppAppConfigVersion
from .service_appconfigtemplatetype import ServiceAppConfigTemplateType
from nuon.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ServiceAppConfigTemplateTypedDict(TypedDict):
    content: NotRequired[str]
    filename: NotRequired[str]
    format_: NotRequired[AppAppConfigVersion]
    type: NotRequired[ServiceAppConfigTemplateType]


class ServiceAppConfigTemplate(BaseModel):
    content: Optional[str] = None

    filename: Optional[str] = None

    format_: Annotated[
        Optional[AppAppConfigVersion], pydantic.Field(alias="format")
    ] = None

    type: Optional[ServiceAppConfigTemplateType] = None
