"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateComponentBuildRequestTypedDict(TypedDict):
    git_ref: NotRequired[str]
    use_latest: NotRequired[bool]


class ServiceCreateComponentBuildRequest(BaseModel):
    git_ref: Optional[str] = None

    use_latest: Optional[bool] = None
