"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_workflowstepresponsetype import AppWorkflowStepResponseType
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateWorkflowStepApprovalResponseRequestTypedDict(TypedDict):
    note: NotRequired[str]
    response_type: NotRequired[AppWorkflowStepResponseType]


class ServiceCreateWorkflowStepApprovalResponseRequest(BaseModel):
    note: Optional[str] = None

    response_type: Optional[AppWorkflowStepResponseType] = None
