"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_stacktype import AppStackType
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateAppStackConfigRequestTypedDict(TypedDict):
    app_config_id: str
    description: str
    name: str
    type: AppStackType
    runner_nested_template_url: NotRequired[str]
    vpc_nested_template_url: NotRequired[str]


class ServiceCreateAppStackConfigRequest(BaseModel):
    app_config_id: str

    description: str

    name: str

    type: AppStackType

    runner_nested_template_url: Optional[str] = None

    vpc_nested_template_url: Optional[str] = None
