"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_connectedgithubvcsconfigrequest import (
    ServiceConnectedGithubVCSConfigRequest,
    ServiceConnectedGithubVCSConfigRequestTypedDict,
)
from .service_publicgitvcsconfigrequest import (
    ServicePublicGitVCSConfigRequest,
    ServicePublicGitVCSConfigRequestTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateDockerBuildComponentConfigRequestTypedDict(TypedDict):
    dockerfile: str
    app_config_id: NotRequired[str]
    build_args: NotRequired[List[str]]
    checksum: NotRequired[str]
    connected_github_vcs_config: NotRequired[
        ServiceConnectedGithubVCSConfigRequestTypedDict
    ]
    dependencies: NotRequired[List[str]]
    env_vars: NotRequired[Dict[str, str]]
    public_git_vcs_config: NotRequired[ServicePublicGitVCSConfigRequestTypedDict]
    references: NotRequired[List[str]]
    target: NotRequired[str]


class ServiceCreateDockerBuildComponentConfigRequest(BaseModel):
    dockerfile: str

    app_config_id: Optional[str] = None

    build_args: Optional[List[str]] = None

    checksum: Optional[str] = None

    connected_github_vcs_config: Optional[ServiceConnectedGithubVCSConfigRequest] = None

    dependencies: Optional[List[str]] = None

    env_vars: Optional[Dict[str, str]] = None

    public_git_vcs_config: Optional[ServicePublicGitVCSConfigRequest] = None

    references: Optional[List[str]] = None

    target: Optional[str] = None
