"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceCreateAppActionWorkflowRequestTypedDict(TypedDict):
    name: NotRequired[str]


class ServiceCreateAppActionWorkflowRequest(BaseModel):
    name: Optional[str] = None
