"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .helpers_createinstallconfigparams import (
    HelpersCreateInstallConfigParams,
    HelpersCreateInstallConfigParamsTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AwsAccountTypedDict(TypedDict):
    iam_role_arn: NotRequired[str]
    region: NotRequired[str]


class AwsAccount(BaseModel):
    iam_role_arn: Optional[str] = None

    region: Optional[str] = None


class AzureAccountTypedDict(TypedDict):
    location: NotRequired[str]
    service_principal_app_id: NotRequired[str]
    service_principal_password: NotRequired[str]
    subscription_id: NotRequired[str]
    subscription_tenant_id: NotRequired[str]


class AzureAccount(BaseModel):
    location: Optional[str] = None

    service_principal_app_id: Optional[str] = None

    service_principal_password: Optional[str] = None

    subscription_id: Optional[str] = None

    subscription_tenant_id: Optional[str] = None


class ServiceCreateInstallRequestTypedDict(TypedDict):
    name: str
    aws_account: NotRequired[AwsAccountTypedDict]
    azure_account: NotRequired[AzureAccountTypedDict]
    inputs: NotRequired[Dict[str, str]]
    install_config: NotRequired[HelpersCreateInstallConfigParamsTypedDict]


class ServiceCreateInstallRequest(BaseModel):
    name: str

    aws_account: Optional[AwsAccount] = None

    azure_account: Optional[AzureAccount] = None

    inputs: Optional[Dict[str, str]] = None

    install_config: Optional[HelpersCreateInstallConfigParams] = None
