"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ServiceReadmeTypedDict(TypedDict):
    original: NotRequired[str]
    readme: NotRequired[str]
    warnings: NotRequired[List[str]]


class ServiceReadme(BaseModel):
    original: Optional[str] = None

    readme: Optional[str] = None

    warnings: Optional[List[str]] = None
