"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class StateInputsStateTypedDict(TypedDict):
    inputs: NotRequired[Dict[str, str]]
    populated: NotRequired[bool]


class StateInputsState(BaseModel):
    inputs: Optional[Dict[str, str]] = None

    populated: Optional[bool] = None
