"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class StateInstallStackStateTypedDict(TypedDict):
    checksum: NotRequired[str]
    outputs: NotRequired[Dict[str, str]]
    populated: NotRequired[bool]
    quick_link_url: NotRequired[str]
    status: NotRequired[str]
    template_json: NotRequired[str]
    template_url: NotRequired[str]


class StateInstallStackState(BaseModel):
    checksum: Optional[str] = None

    outputs: Optional[Dict[str, str]] = None

    populated: Optional[bool] = None

    quick_link_url: Optional[str] = None

    status: Optional[str] = None

    template_json: Optional[str] = None

    template_url: Optional[str] = None
