"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class StateSandboxStateTypedDict(TypedDict):
    outputs: NotRequired[Dict[str, Any]]
    populated: NotRequired[bool]
    recent_runs: NotRequired[List[StateSandboxStateTypedDict]]
    status: NotRequired[str]
    type: NotRequired[str]
    version: NotRequired[str]


class StateSandboxState(BaseModel):
    outputs: Optional[Dict[str, Any]] = None

    populated: Optional[bool] = None

    recent_runs: Optional[List[StateSandboxState]] = None

    status: Optional[str] = None

    type: Optional[str] = None

    version: Optional[str] = None
