"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nuon.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StateRunnerStateTypedDict(TypedDict):
    id: NotRequired[str]
    populated: NotRequired[bool]
    runner_group_id: NotRequired[str]
    status: NotRequired[str]


class StateRunnerState(BaseModel):
    id: Optional[str] = None

    populated: Optional[bool] = None

    runner_group_id: Optional[str] = None

    status: Optional[str] = None
