"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .state_actionworkflowstate import (
    StateActionWorkflowState,
    StateActionWorkflowStateTypedDict,
)
from nuon.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class StateActionsStateTypedDict(TypedDict):
    populated: NotRequired[bool]
    workflows: NotRequired[Dict[str, StateActionWorkflowStateTypedDict]]


class StateActionsState(BaseModel):
    populated: Optional[bool] = None

    workflows: Optional[Dict[str, StateActionWorkflowState]] = None
