"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_teardowninstallcomponentrequest import (
    ServiceTeardownInstallComponentRequest,
    ServiceTeardownInstallComponentRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TeardownInstallComponentSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class TeardownInstallComponentSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class TeardownInstallComponentRequestTypedDict(TypedDict):
    install_id: str
    r"""install ID"""
    component_id: str
    r"""component ID"""
    service_teardown_install_component_request: NotRequired[
        ServiceTeardownInstallComponentRequestTypedDict
    ]
    r"""Input"""


class TeardownInstallComponentRequest(BaseModel):
    install_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""install ID"""

    component_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""component ID"""

    service_teardown_install_component_request: Annotated[
        Optional[ServiceTeardownInstallComponentRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Input"""
