"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_updaterunnersettingsrequest import (
    ServiceUpdateRunnerSettingsRequest,
    ServiceUpdateRunnerSettingsRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateRunnerSettingsSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class UpdateRunnerSettingsSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class UpdateRunnerSettingsRequestTypedDict(TypedDict):
    runner_id: str
    r"""runner ID"""
    service_update_runner_settings_request: ServiceUpdateRunnerSettingsRequestTypedDict
    r"""Input"""


class UpdateRunnerSettingsRequest(BaseModel):
    runner_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""runner ID"""

    service_update_runner_settings_request: Annotated[
        ServiceUpdateRunnerSettingsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
