"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_updateworkflowrequest import (
    ServiceUpdateWorkflowRequest,
    ServiceUpdateWorkflowRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateWorkflowSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class UpdateWorkflowSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class UpdateWorkflowRequestTypedDict(TypedDict):
    workflow_id: str
    r"""workflow ID"""
    service_update_workflow_request: ServiceUpdateWorkflowRequestTypedDict
    r"""Input"""


class UpdateWorkflowRequest(BaseModel):
    workflow_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""workflow ID"""

    service_update_workflow_request: Annotated[
        ServiceUpdateWorkflowRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
