"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .service_updateinstallerrequest import (
    ServiceUpdateInstallerRequest,
    ServiceUpdateInstallerRequestTypedDict,
)
from nuon.types import BaseModel
from nuon.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateInstallerSecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    org_id: NotRequired[str]


class UpdateInstallerSecurity(BaseModel):
    api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None

    org_id: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Nuon-Org-ID",
            )
        ),
    ] = None


class UpdateInstallerRequestTypedDict(TypedDict):
    installer_id: str
    r"""installer ID"""
    service_update_installer_request: ServiceUpdateInstallerRequestTypedDict
    r"""Input"""


class UpdateInstallerRequest(BaseModel):
    installer_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""installer ID"""

    service_update_installer_request: Annotated[
        ServiceUpdateInstallerRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Input"""
