from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.app_account import AppAccount
    from ..models.app_composite_status import AppCompositeStatus
    from ..models.app_install_runbook import AppInstallRunbook
    from ..models.app_install_runbook_run_runbook_inputs import AppInstallRunbookRunRunbookInputs
    from ..models.app_install_runbook_run_runbook_inputs_redacted import AppInstallRunbookRunRunbookInputsRedacted
    from ..models.app_runbook_config import AppRunbookConfig
    from ..models.app_runbook_step_selection import AppRunbookStepSelection
    from ..models.app_workflow import AppWorkflow


T = TypeVar("T", bound="AppInstallRunbookRun")


@_attrs_define
class AppInstallRunbookRun:
    """
    Attributes:
        created_at (str | Unset):
        created_by (AppAccount | Unset):
        created_by_id (str | Unset):
        execution_time (int | Unset): after query
        id (str | Unset):
        install_id (str | Unset):
        install_runbook (AppInstallRunbook | Unset):
        install_runbook_id (str | Unset):
        install_workflow (AppWorkflow | Unset):
        install_workflow_id (str | Unset):
        runbook_config (AppRunbookConfig | Unset):
        runbook_config_id (str | Unset):
        runbook_inputs (AppInstallRunbookRunRunbookInputs | Unset):
        runbook_inputs_redacted (AppInstallRunbookRunRunbookInputsRedacted | Unset):
        status (str | Unset):
        status_description (str | Unset):
        status_v2 (AppCompositeStatus | Unset):
        step_selections (list[AppRunbookStepSelection] | Unset): StepSelections records which runbook steps are
            enabled/disabled for this run.
            Steps explicitly disabled here are not generated by the runbook workflow.
        triggered_by_id (str | Unset):
        updated_at (str | Unset):
    """

    created_at: str | Unset = UNSET
    created_by: AppAccount | Unset = UNSET
    created_by_id: str | Unset = UNSET
    execution_time: int | Unset = UNSET
    id: str | Unset = UNSET
    install_id: str | Unset = UNSET
    install_runbook: AppInstallRunbook | Unset = UNSET
    install_runbook_id: str | Unset = UNSET
    install_workflow: AppWorkflow | Unset = UNSET
    install_workflow_id: str | Unset = UNSET
    runbook_config: AppRunbookConfig | Unset = UNSET
    runbook_config_id: str | Unset = UNSET
    runbook_inputs: AppInstallRunbookRunRunbookInputs | Unset = UNSET
    runbook_inputs_redacted: AppInstallRunbookRunRunbookInputsRedacted | Unset = UNSET
    status: str | Unset = UNSET
    status_description: str | Unset = UNSET
    status_v2: AppCompositeStatus | Unset = UNSET
    step_selections: list[AppRunbookStepSelection] | Unset = UNSET
    triggered_by_id: str | Unset = UNSET
    updated_at: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        created_at = self.created_at

        created_by: dict[str, Any] | Unset = UNSET
        if not isinstance(self.created_by, Unset):
            created_by = self.created_by.to_dict()

        created_by_id = self.created_by_id

        execution_time = self.execution_time

        id = self.id

        install_id = self.install_id

        install_runbook: dict[str, Any] | Unset = UNSET
        if not isinstance(self.install_runbook, Unset):
            install_runbook = self.install_runbook.to_dict()

        install_runbook_id = self.install_runbook_id

        install_workflow: dict[str, Any] | Unset = UNSET
        if not isinstance(self.install_workflow, Unset):
            install_workflow = self.install_workflow.to_dict()

        install_workflow_id = self.install_workflow_id

        runbook_config: dict[str, Any] | Unset = UNSET
        if not isinstance(self.runbook_config, Unset):
            runbook_config = self.runbook_config.to_dict()

        runbook_config_id = self.runbook_config_id

        runbook_inputs: dict[str, Any] | Unset = UNSET
        if not isinstance(self.runbook_inputs, Unset):
            runbook_inputs = self.runbook_inputs.to_dict()

        runbook_inputs_redacted: dict[str, Any] | Unset = UNSET
        if not isinstance(self.runbook_inputs_redacted, Unset):
            runbook_inputs_redacted = self.runbook_inputs_redacted.to_dict()

        status = self.status

        status_description = self.status_description

        status_v2: dict[str, Any] | Unset = UNSET
        if not isinstance(self.status_v2, Unset):
            status_v2 = self.status_v2.to_dict()

        step_selections: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.step_selections, Unset):
            step_selections = []
            for step_selections_item_data in self.step_selections:
                step_selections_item = step_selections_item_data.to_dict()
                step_selections.append(step_selections_item)

        triggered_by_id = self.triggered_by_id

        updated_at = self.updated_at

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if created_by is not UNSET:
            field_dict["created_by"] = created_by
        if created_by_id is not UNSET:
            field_dict["created_by_id"] = created_by_id
        if execution_time is not UNSET:
            field_dict["execution_time"] = execution_time
        if id is not UNSET:
            field_dict["id"] = id
        if install_id is not UNSET:
            field_dict["install_id"] = install_id
        if install_runbook is not UNSET:
            field_dict["install_runbook"] = install_runbook
        if install_runbook_id is not UNSET:
            field_dict["install_runbook_id"] = install_runbook_id
        if install_workflow is not UNSET:
            field_dict["install_workflow"] = install_workflow
        if install_workflow_id is not UNSET:
            field_dict["install_workflow_id"] = install_workflow_id
        if runbook_config is not UNSET:
            field_dict["runbook_config"] = runbook_config
        if runbook_config_id is not UNSET:
            field_dict["runbook_config_id"] = runbook_config_id
        if runbook_inputs is not UNSET:
            field_dict["runbook_inputs"] = runbook_inputs
        if runbook_inputs_redacted is not UNSET:
            field_dict["runbook_inputs_redacted"] = runbook_inputs_redacted
        if status is not UNSET:
            field_dict["status"] = status
        if status_description is not UNSET:
            field_dict["status_description"] = status_description
        if status_v2 is not UNSET:
            field_dict["status_v2"] = status_v2
        if step_selections is not UNSET:
            field_dict["step_selections"] = step_selections
        if triggered_by_id is not UNSET:
            field_dict["triggered_by_id"] = triggered_by_id
        if updated_at is not UNSET:
            field_dict["updated_at"] = updated_at

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.app_account import AppAccount
        from ..models.app_composite_status import AppCompositeStatus
        from ..models.app_install_runbook import AppInstallRunbook
        from ..models.app_install_runbook_run_runbook_inputs import AppInstallRunbookRunRunbookInputs
        from ..models.app_install_runbook_run_runbook_inputs_redacted import AppInstallRunbookRunRunbookInputsRedacted
        from ..models.app_runbook_config import AppRunbookConfig
        from ..models.app_runbook_step_selection import AppRunbookStepSelection
        from ..models.app_workflow import AppWorkflow

        d = dict(src_dict)
        created_at = d.pop("created_at", UNSET)

        _created_by = d.pop("created_by", UNSET)
        created_by: AppAccount | Unset
        if isinstance(_created_by, Unset):
            created_by = UNSET
        else:
            created_by = AppAccount.from_dict(_created_by)

        created_by_id = d.pop("created_by_id", UNSET)

        execution_time = d.pop("execution_time", UNSET)

        id = d.pop("id", UNSET)

        install_id = d.pop("install_id", UNSET)

        _install_runbook = d.pop("install_runbook", UNSET)
        install_runbook: AppInstallRunbook | Unset
        if isinstance(_install_runbook, Unset):
            install_runbook = UNSET
        else:
            install_runbook = AppInstallRunbook.from_dict(_install_runbook)

        install_runbook_id = d.pop("install_runbook_id", UNSET)

        _install_workflow = d.pop("install_workflow", UNSET)
        install_workflow: AppWorkflow | Unset
        if isinstance(_install_workflow, Unset):
            install_workflow = UNSET
        else:
            install_workflow = AppWorkflow.from_dict(_install_workflow)

        install_workflow_id = d.pop("install_workflow_id", UNSET)

        _runbook_config = d.pop("runbook_config", UNSET)
        runbook_config: AppRunbookConfig | Unset
        if isinstance(_runbook_config, Unset):
            runbook_config = UNSET
        else:
            runbook_config = AppRunbookConfig.from_dict(_runbook_config)

        runbook_config_id = d.pop("runbook_config_id", UNSET)

        _runbook_inputs = d.pop("runbook_inputs", UNSET)
        runbook_inputs: AppInstallRunbookRunRunbookInputs | Unset
        if isinstance(_runbook_inputs, Unset):
            runbook_inputs = UNSET
        else:
            runbook_inputs = AppInstallRunbookRunRunbookInputs.from_dict(_runbook_inputs)

        _runbook_inputs_redacted = d.pop("runbook_inputs_redacted", UNSET)
        runbook_inputs_redacted: AppInstallRunbookRunRunbookInputsRedacted | Unset
        if isinstance(_runbook_inputs_redacted, Unset):
            runbook_inputs_redacted = UNSET
        else:
            runbook_inputs_redacted = AppInstallRunbookRunRunbookInputsRedacted.from_dict(_runbook_inputs_redacted)

        status = d.pop("status", UNSET)

        status_description = d.pop("status_description", UNSET)

        _status_v2 = d.pop("status_v2", UNSET)
        status_v2: AppCompositeStatus | Unset
        if isinstance(_status_v2, Unset):
            status_v2 = UNSET
        else:
            status_v2 = AppCompositeStatus.from_dict(_status_v2)

        _step_selections = d.pop("step_selections", UNSET)
        step_selections: list[AppRunbookStepSelection] | Unset = UNSET
        if _step_selections is not UNSET:
            step_selections = []
            for step_selections_item_data in _step_selections:
                step_selections_item = AppRunbookStepSelection.from_dict(step_selections_item_data)

                step_selections.append(step_selections_item)

        triggered_by_id = d.pop("triggered_by_id", UNSET)

        updated_at = d.pop("updated_at", UNSET)

        app_install_runbook_run = cls(
            created_at=created_at,
            created_by=created_by,
            created_by_id=created_by_id,
            execution_time=execution_time,
            id=id,
            install_id=install_id,
            install_runbook=install_runbook,
            install_runbook_id=install_runbook_id,
            install_workflow=install_workflow,
            install_workflow_id=install_workflow_id,
            runbook_config=runbook_config,
            runbook_config_id=runbook_config_id,
            runbook_inputs=runbook_inputs,
            runbook_inputs_redacted=runbook_inputs_redacted,
            status=status,
            status_description=status_description,
            status_v2=status_v2,
            step_selections=step_selections,
            triggered_by_id=triggered_by_id,
            updated_at=updated_at,
        )

        app_install_runbook_run.additional_properties = d
        return app_install_runbook_run

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
