from enum import StrEnum


class AppActionWorkflowTriggerType(StrEnum):
    ACTION_WORKFLOW_TRIGGER_TYPE_AD_HOC = "adhoc"
    ACTION_WORKFLOW_TRIGGER_TYPE_CRON = "cron"
    ACTION_WORKFLOW_TRIGGER_TYPE_MANUAL = "manual"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_DEPLOY_ALL_COMPONENTS = "post-deploy-all-components"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_DEPLOY_COMPONENT = "post-deploy-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_DEPROVISION = "post-deprovision"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_DEPROVISION_SANDBOX = "post-deprovision-sandbox"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_DISABLE_COMPONENT = "post-disable-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_ENABLE_COMPONENT = "post-enable-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_PROVISION = "post-provision"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_PROVISION_SANDBOX = "post-provision-sandbox"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_REPROVISION = "post-reprovision"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_REPROVISION_SANDBOX = "post-reprovision-sandbox"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_SECRETS_SYNC = "post-secrets-sync"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_TEARDOWN_ALL_COMPONENTS = "post-teardown-all-components"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_TEARDOWN_COMPONENT = "post-teardown-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_POST_UPDATE_INPUTS = "post-update-inputs"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_DEPLOY_ALL_COMPONENTS = "pre-deploy-all-components"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_DEPLOY_COMPONENT = "pre-deploy-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_DEPROVISION = "pre-deprovision"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_DEPROVISION_SANDBOX = "pre-deprovision-sandbox"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_DISABLE_COMPONENT = "pre-disable-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_ENABLE_COMPONENT = "pre-enable-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_PROVISION = "pre-provision"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_REPROVISION = "pre-reprovision"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_REPROVISION_SANDBOX = "pre-reprovision-sandbox"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_SECRETS_SYNC = "pre-secrets-sync"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_TEARDOWN_ALL_COMPONENTS = "pre-teardown-all-components"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_TEARDOWN_COMPONENT = "pre-teardown-component"
    ACTION_WORKFLOW_TRIGGER_TYPE_PRE_UPDATE_INPUTS = "pre-update-inputs"
    ACTION_WORKFLOW_TRIGGER_TYPE_ROLE_DISABLED = "role-disabled"
    ACTION_WORKFLOW_TRIGGER_TYPE_ROLE_ENABLED = "role-enabled"

    def __str__(self) -> str:
        return str(self.value)
