from enum import StrEnum


class AppRunnerJobType(StrEnum):
    RUNNER_JOB_TYPE_ACTIONS_WORKFLOW_RUN = "actions-workflow"
    RUNNER_JOB_TYPE_CONTAINER_IMAGE_BUILD = "container-image-build"
    RUNNER_JOB_TYPE_DOCKER_BUILD = "docker-build"
    RUNNER_JOB_TYPE_FETCH_IMAGE_METADATA = "fetch-image-metadata"
    RUNNER_JOB_TYPE_HEALTH_CHECK = "health-check"
    RUNNER_JOB_TYPE_HELM_CHART_BUILD = "helm-chart-build"
    RUNNER_JOB_TYPE_HELM_CHART_DEPLOY = "helm-chart-deploy"
    RUNNER_JOB_TYPE_JOB_DEPLOY = "job-deploy"
    RUNNER_JOB_TYPE_JOB_NOOP_DEPLOY = "noop-deploy"
    RUNNER_JOB_TYPE_KUBERNETES_MANIFEST_BUILD = "kubernetes-manifest-build"
    RUNNER_JOB_TYPE_KUBRENETES_MANIFEST_DEPLOY = "kubernetes-manifest-deploy"
    RUNNER_JOB_TYPE_MNG_FETCH_TOKEN = "mng-fetch-token"
    RUNNER_JOB_TYPE_MNG_RUNNER_RESTART = "mng-runner-restart"
    RUNNER_JOB_TYPE_MNG_RUNNER_UPDATE_VERSION = "mng-runner-update-version"
    RUNNER_JOB_TYPE_MNG_SHUT_DOWN = "mng-shut-down"
    RUNNER_JOB_TYPE_MNG_VM_SHUT_DOWN = "mng-vm-shut-down"
    RUNNER_JOB_TYPE_NOOP = "noop"
    RUNNER_JOB_TYPE_NOOP_BUILD = "noop-build"
    RUNNER_JOB_TYPE_NOOP_SYNC = "noop-sync"
    RUNNER_JOB_TYPE_OCI_SYNC = "oci-sync"
    RUNNER_JOB_TYPE_PULUMI_BUILD = "pulumi-build"
    RUNNER_JOB_TYPE_PULUMI_DEPLOY = "pulumi-deploy"
    RUNNER_JOB_TYPE_RUNNER_HELM = "runner-helm"
    RUNNER_JOB_TYPE_RUNNER_LOCAL = "runner-local"
    RUNNER_JOB_TYPE_RUNNER_TERRAFORM = "runner-terraform"
    RUNNER_JOB_TYPE_SANDBOX_BUILD = "sandbox-build"
    RUNNER_JOB_TYPE_SANDBOX_PULUMI = "sandbox-pulumi"
    RUNNER_JOB_TYPE_SANDBOX_SYNC_SECRETS = "sandbox-sync-secrets"
    RUNNER_JOB_TYPE_SANDBOX_TERRAFORM = "sandbox-terraform"
    RUNNER_JOB_TYPE_SANDBOX_TERRAFORM_PLAN = "sandbox-terraform-plan"
    RUNNER_JOB_TYPE_SHUT_DOWN = "shut-down"
    RUNNER_JOB_TYPE_TERRAFORM_DEPLOY = "terraform-deploy"
    RUNNER_JOB_TYPE_TERRAFORM_MODULE_BUILD = "terraform-module-build"
    RUNNER_JOB_TYPE_UPDATE_VERSION = "update-version"

    def __str__(self) -> str:
        return str(self.value)
