# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuon.models.app_component import AppComponent
from nuon.models.app_component_build_status import AppComponentBuildStatus
from nuon.models.app_component_config_connection import AppComponentConfigConnection
from nuon.models.app_install_deploy_status import AppInstallDeployStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppInstallComponentSummary(BaseModel):
    """
    AppInstallComponentSummary
    """ # noqa: E501
    build_status: Optional[AppComponentBuildStatus] = None
    build_status_description: Optional[StrictStr] = None
    component_config: Optional[AppComponentConfigConnection] = None
    component_id: Optional[StrictStr] = None
    component_name: Optional[StrictStr] = None
    dependencies: Optional[List[AppComponent]] = None
    deploy_status: Optional[AppInstallDeployStatus] = None
    deploy_status_description: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["build_status", "build_status_description", "component_config", "component_id", "component_name", "dependencies", "deploy_status", "deploy_status_description", "id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppInstallComponentSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of component_config
        if self.component_config:
            _dict['component_config'] = self.component_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in dependencies (list)
        _items = []
        if self.dependencies:
            for _item in self.dependencies:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dependencies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppInstallComponentSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "build_status": obj.get("build_status"),
            "build_status_description": obj.get("build_status_description"),
            "component_config": AppComponentConfigConnection.from_dict(obj.get("component_config")) if obj.get("component_config") is not None else None,
            "component_id": obj.get("component_id"),
            "component_name": obj.get("component_name"),
            "dependencies": [AppComponent.from_dict(_item) for _item in obj.get("dependencies")] if obj.get("dependencies") is not None else None,
            "deploy_status": obj.get("deploy_status"),
            "deploy_status_description": obj.get("deploy_status_description"),
            "id": obj.get("id")
        })
        return _obj


