# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AppRunnerStatus(str, Enum):
    """
    AppRunnerStatus
    """

    """
    allowed enum values
    """
    ERROR = 'error'
    ACTIVE = 'active'
    PENDING = 'pending'
    PROVISIONING = 'provisioning'
    DEPROVISIONING = 'deprovisioning'
    DEPROVISIONED = 'deprovisioned'
    REPROVISIONING = 'reprovisioning'
    OFFLINE = 'offline'
    AWAITING_MINUS_INSTALL_MINUS_STACK_MINUS_RUN = 'awaiting-install-stack-run'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppRunnerStatus from a JSON string"""
        return cls(json.loads(json_str))


