# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AppWorkflowStepApprovalType(str, Enum):
    """
    AppWorkflowStepApprovalType
    """

    """
    allowed enum values
    """
    NOOP = 'noop'
    APPROVE_MINUS_ALL = 'approve-all'
    TERRAFORM_PLAN = 'terraform_plan'
    KUBERNETES_MANIFEST_APPROVAL = 'kubernetes_manifest_approval'
    HELM_APPROVAL = 'helm_approval'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppWorkflowStepApprovalType from a JSON string"""
        return cls(json.loads(json_str))


