from enum import StrEnum


class AppStatus(StrEnum):
    AWAITING_APPROVAL = "approval-awaiting"
    INSTALL_DEPLOY_STATUS_V2_NOOP = "noop"
    INSTALL_STACK_VERSION_STATUS_ACTIVE = "active"
    INSTALL_STACK_VERSION_STATUS_EXPIRED = "expired"
    INSTALL_STACK_VERSION_STATUS_GENERATING = "generating"
    INSTALL_STACK_VERSION_STATUS_OUTDATED = "outdated"
    INSTALL_STACK_VERSION_STATUS_PENDING_USER = "awaiting-user-run"
    INSTALL_STACK_VERSION_STATUS_PROVISIONING = "provisioning"
    STATUS_APPLYING = "applying"
    STATUS_AUTO_SKIPPED = "auto-skipped"
    STATUS_BUILDING = "building"
    STATUS_CANCELLED = "cancelled"
    STATUS_CHECK_PLAN = "checking-plan"
    STATUS_DELETING = "deleting"
    STATUS_DISABLED = "disabled"
    STATUS_DISCARDED = "discarded"
    STATUS_ERROR = "error"
    STATUS_FAILED_PENDING_RETRY = "failed-pending-retry"
    STATUS_IN_PROGRESS = "in-progress"
    STATUS_NOT_ATTEMPTED = "not-attempted"
    STATUS_PENDING = "pending"
    STATUS_PLANNING = "planning"
    STATUS_QUEUED = "queued"
    STATUS_RETRYING = "retrying"
    STATUS_SUCCESS = "success"
    STATUS_USER_SKIPPED = "user-skipped"
    STATUS_WARNING = "warning"
    WORKFLOW_STEP_APPROVAL_STATUS_APPROVAL_DENIED = "approval-denied"
    WORKFLOW_STEP_APPROVAL_STATUS_APPROVAL_EXPIRED = "approval-expired"
    WORKFLOW_STEP_APPROVAL_STATUS_APPROVAL_RETRY_PLAN = "approval-retry"
    WORKFLOW_STEP_APPROVAL_STATUS_APPROVED = "approved"
    WORKFLOW_STEP_DRIFTED = "drifted"
    WORKFLOW_STEP_NO_DRIFT = "no-drift"

    def __str__(self) -> str:
        return str(self.value)
