# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuon.models.app_action_workflow import AppActionWorkflow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppInstallActionWorkflow(BaseModel):
    """
    AppInstallActionWorkflow
    """ # noqa: E501
    action_workflow: Optional[AppActionWorkflow] = None
    action_workflow_id: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    created_by_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    install_id: Optional[StrictStr] = None
    runs: Optional[List[AppInstallActionWorkflowRun]] = None
    status: Optional[StrictStr] = Field(default=None, description="after query fields filled in after querying")
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["action_workflow", "action_workflow_id", "created_at", "created_by_id", "id", "install_id", "runs", "status", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppInstallActionWorkflow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action_workflow
        if self.action_workflow:
            _dict['action_workflow'] = self.action_workflow.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in runs (list)
        _items = []
        if self.runs:
            for _item in self.runs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['runs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppInstallActionWorkflow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action_workflow": AppActionWorkflow.from_dict(obj.get("action_workflow")) if obj.get("action_workflow") is not None else None,
            "action_workflow_id": obj.get("action_workflow_id"),
            "created_at": obj.get("created_at"),
            "created_by_id": obj.get("created_by_id"),
            "id": obj.get("id"),
            "install_id": obj.get("install_id"),
            "runs": [AppInstallActionWorkflowRun.from_dict(_item) for _item in obj.get("runs")] if obj.get("runs") is not None else None,
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at")
        })
        return _obj

from nuon.models.app_install_action_workflow_run import AppInstallActionWorkflowRun
# TODO: Rewrite to not use raise_errors
AppInstallActionWorkflow.model_rebuild(raise_errors=False)

