# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppHelmRelease(BaseModel):
    """
    AppHelmRelease
    """ # noqa: E501
    body: Optional[StrictStr] = Field(default=None, description="The rspb.Release body, as a base64-encoded string")
    created_at: Optional[StrictStr] = None
    created_by_id: Optional[StrictStr] = None
    helm_chart: Optional[AppHelmChart] = Field(default=None, alias="helmChart")
    helm_chart_id: Optional[StrictStr] = Field(default=None, alias="helmChartID")
    key: Optional[StrictStr] = None
    labels: Optional[Dict[str, StrictStr]] = None
    name: Optional[StrictStr] = Field(default=None, description="Release \"labels\" that can be used as filters in the storage.Query(labels map[string]string) we implemented. Note that allowing Helm users to filter against new dimensions will require a new migration to be added, and the Create and/or update functions to be updated accordingly.")
    namespace: Optional[StrictStr] = None
    org_id: Optional[StrictStr] = None
    owner: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    type: Optional[StrictStr] = Field(default=None, description="See https://github.com/helm/helm/blob/c9fe3d118caec699eb2565df9838673af379ce12/pkg/storage/driver/secrets.go#L231")
    updated_at: Optional[StrictStr] = None
    version: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["body", "created_at", "created_by_id", "helmChart", "helmChartID", "key", "labels", "name", "namespace", "org_id", "owner", "status", "type", "updated_at", "version"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppHelmRelease from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of helm_chart
        if self.helm_chart:
            _dict['helmChart'] = self.helm_chart.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppHelmRelease from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "body": obj.get("body"),
            "created_at": obj.get("created_at"),
            "created_by_id": obj.get("created_by_id"),
            "helmChart": AppHelmChart.from_dict(obj.get("helmChart")) if obj.get("helmChart") is not None else None,
            "helmChartID": obj.get("helmChartID"),
            "key": obj.get("key"),
            "labels": obj.get("labels"),
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "org_id": obj.get("org_id"),
            "owner": obj.get("owner"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "version": obj.get("version")
        })
        return _obj

from nuon.models.app_helm_chart import AppHelmChart
# TODO: Rewrite to not use raise_errors
AppHelmRelease.model_rebuild(raise_errors=False)

