# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuon.models.app_account import AppAccount
from nuon.models.app_component_config_connection import AppComponentConfigConnection
from nuon.models.app_composite_status import AppCompositeStatus
from nuon.models.app_log_stream import AppLogStream
from nuon.models.app_runner_job import AppRunnerJob
from nuon.models.app_vcs_connection_commit import AppVCSConnectionCommit
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppComponentBuild(BaseModel):
    """
    AppComponentBuild
    """ # noqa: E501
    checksum: Optional[StrictStr] = Field(default=None, description="checksum of our intermediate component config")
    component_config_connection: Optional[AppComponentConfigConnection] = None
    component_config_connection_id: Optional[StrictStr] = Field(default=None, description="DEPRECATED: will retain the field to connect against the last component config connection that set this build")
    component_config_version: Optional[StrictInt] = None
    component_id: Optional[StrictStr] = Field(default=None, description="Read-only fields set on the object to de-nest data")
    component_name: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    created_by: Optional[AppAccount] = None
    created_by_id: Optional[StrictStr] = None
    git_ref: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    install_deploys: Optional[List[AppInstallDeploy]] = None
    log_stream: Optional[AppLogStream] = None
    releases: Optional[List[AppComponentRelease]] = None
    runner_job: Optional[AppRunnerJob] = Field(default=None, description="runner details")
    status: Optional[StrictStr] = None
    status_description: Optional[StrictStr] = None
    status_v2: Optional[AppCompositeStatus] = None
    updated_at: Optional[StrictStr] = None
    vcs_connection_commit: Optional[AppVCSConnectionCommit] = None
    __properties: ClassVar[List[str]] = ["checksum", "component_config_connection", "component_config_connection_id", "component_config_version", "component_id", "component_name", "created_at", "created_by", "created_by_id", "git_ref", "id", "install_deploys", "log_stream", "releases", "runner_job", "status", "status_description", "status_v2", "updated_at", "vcs_connection_commit"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppComponentBuild from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of component_config_connection
        if self.component_config_connection:
            _dict['component_config_connection'] = self.component_config_connection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in install_deploys (list)
        _items = []
        if self.install_deploys:
            for _item in self.install_deploys:
                if _item:
                    _items.append(_item.to_dict())
            _dict['install_deploys'] = _items
        # override the default output from pydantic by calling `to_dict()` of log_stream
        if self.log_stream:
            _dict['log_stream'] = self.log_stream.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in releases (list)
        _items = []
        if self.releases:
            for _item in self.releases:
                if _item:
                    _items.append(_item.to_dict())
            _dict['releases'] = _items
        # override the default output from pydantic by calling `to_dict()` of runner_job
        if self.runner_job:
            _dict['runner_job'] = self.runner_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status_v2
        if self.status_v2:
            _dict['status_v2'] = self.status_v2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vcs_connection_commit
        if self.vcs_connection_commit:
            _dict['vcs_connection_commit'] = self.vcs_connection_commit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppComponentBuild from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checksum": obj.get("checksum"),
            "component_config_connection": AppComponentConfigConnection.from_dict(obj.get("component_config_connection")) if obj.get("component_config_connection") is not None else None,
            "component_config_connection_id": obj.get("component_config_connection_id"),
            "component_config_version": obj.get("component_config_version"),
            "component_id": obj.get("component_id"),
            "component_name": obj.get("component_name"),
            "created_at": obj.get("created_at"),
            "created_by": AppAccount.from_dict(obj.get("created_by")) if obj.get("created_by") is not None else None,
            "created_by_id": obj.get("created_by_id"),
            "git_ref": obj.get("git_ref"),
            "id": obj.get("id"),
            "install_deploys": [AppInstallDeploy.from_dict(_item) for _item in obj.get("install_deploys")] if obj.get("install_deploys") is not None else None,
            "log_stream": AppLogStream.from_dict(obj.get("log_stream")) if obj.get("log_stream") is not None else None,
            "releases": [AppComponentRelease.from_dict(_item) for _item in obj.get("releases")] if obj.get("releases") is not None else None,
            "runner_job": AppRunnerJob.from_dict(obj.get("runner_job")) if obj.get("runner_job") is not None else None,
            "status": obj.get("status"),
            "status_description": obj.get("status_description"),
            "status_v2": AppCompositeStatus.from_dict(obj.get("status_v2")) if obj.get("status_v2") is not None else None,
            "updated_at": obj.get("updated_at"),
            "vcs_connection_commit": AppVCSConnectionCommit.from_dict(obj.get("vcs_connection_commit")) if obj.get("vcs_connection_commit") is not None else None
        })
        return _obj

from nuon.models.app_component_release import AppComponentRelease
from nuon.models.app_install_deploy import AppInstallDeploy
# TODO: Rewrite to not use raise_errors
AppComponentBuild.model_rebuild(raise_errors=False)

