# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuon.models.app_composite_status import AppCompositeStatus
from nuon.models.app_install_sandbox_run import AppInstallSandboxRun
from nuon.models.app_terraform_workspace import AppTerraformWorkspace
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppInstallSandbox(BaseModel):
    """
    AppInstallSandbox
    """ # noqa: E501
    created_at: Optional[StrictStr] = None
    created_by_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    install_id: Optional[StrictStr] = None
    install_sandbox_runs: Optional[List[AppInstallSandboxRun]] = None
    status: Optional[StrictStr] = None
    status_description: Optional[StrictStr] = None
    status_v2: Optional[AppCompositeStatus] = None
    terraform_workspace: Optional[AppTerraformWorkspace] = None
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "created_by_id", "id", "install_id", "install_sandbox_runs", "status", "status_description", "status_v2", "terraform_workspace", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppInstallSandbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in install_sandbox_runs (list)
        _items = []
        if self.install_sandbox_runs:
            for _item in self.install_sandbox_runs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['install_sandbox_runs'] = _items
        # override the default output from pydantic by calling `to_dict()` of status_v2
        if self.status_v2:
            _dict['status_v2'] = self.status_v2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of terraform_workspace
        if self.terraform_workspace:
            _dict['terraform_workspace'] = self.terraform_workspace.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppInstallSandbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "created_by_id": obj.get("created_by_id"),
            "id": obj.get("id"),
            "install_id": obj.get("install_id"),
            "install_sandbox_runs": [AppInstallSandboxRun.from_dict(_item) for _item in obj.get("install_sandbox_runs")] if obj.get("install_sandbox_runs") is not None else None,
            "status": obj.get("status"),
            "status_description": obj.get("status_description"),
            "status_v2": AppCompositeStatus.from_dict(obj.get("status_v2")) if obj.get("status_v2") is not None else None,
            "terraform_workspace": AppTerraformWorkspace.from_dict(obj.get("terraform_workspace")) if obj.get("terraform_workspace") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        return _obj


