# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuon.models.app_composite_status import AppCompositeStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AppWorkflowStepPolicyValidation(BaseModel):
    """
    AppWorkflowStepPolicyValidation
    """ # noqa: E501
    created_at: Optional[StrictStr] = None
    created_by_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    install_workflow_step_id: Optional[StrictStr] = Field(default=None, description="install workflow step is the install step that this was performed within")
    response: Optional[StrictStr] = Field(default=None, description="response is the kyverno response")
    runner_job_id: Optional[StrictStr] = Field(default=None, description="runnerJobID is the runner job that this was performed within")
    status: Optional[AppCompositeStatus] = Field(default=None, description="status denotes whether this passed, or whether it failed the job.")
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "created_by_id", "id", "install_workflow_step_id", "response", "runner_job_id", "status", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppWorkflowStepPolicyValidation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AppWorkflowStepPolicyValidation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "created_by_id": obj.get("created_by_id"),
            "id": obj.get("id"),
            "install_workflow_step_id": obj.get("install_workflow_step_id"),
            "response": obj.get("response"),
            "runner_job_id": obj.get("runner_job_id"),
            "status": AppCompositeStatus.from_dict(obj.get("status")) if obj.get("status") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        return _obj


