# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AppRunnerJobOperationType(str, Enum):
    """
    AppRunnerJobOperationType
    """

    """
    allowed enum values
    """
    EXEC = 'exec'
    BUILD = 'build'
    CREATE_MINUS_APPLY_MINUS_PLAN = 'create-apply-plan'
    CREATE_MINUS_TEARDOWN_MINUS_PLAN = 'create-teardown-plan'
    APPLY_MINUS_PLAN = 'apply-plan'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppRunnerJobOperationType from a JSON string"""
        return cls(json.loads(json_str))


