# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, installs, and actions.

    The version of the OpenAPI document: cc3796a
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ConfigAppPolicyType(str, Enum):
    """
    ConfigAppPolicyType
    """

    """
    allowed enum values
    """
    KUBERNETES_CLUSTER = 'kubernetes_cluster'
    RUNNER_JOB_TERRAFORM_DEPLOY = 'runner_job_terraform_deploy'
    RUNNER_JOB_HELM_DEPLOY = 'runner_job_helm_deploy'
    RUNNER_JOB_ACTION_WORKFLOW = 'runner_job_action_workflow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConfigAppPolicyType from a JSON string"""
        return cls(json.loads(json_str))


